# Revolut Fraud FC Case

## Data management

#### Imports

In [342]:
import pandas as pd
import numpy as np

df = pd.read_csv("fraud_prevention_data.csv")
df.head()

                                USER_ID          TYPE  AMOUNT CURRENCY MERCHANT_COUNTRY     KYC  BIRTH_YEAR COUNTRY  IS_FRAUD
0  7285c1ec-31d0-4022-b311-0ad9227ef7f4  CARD_PAYMENT    3738      GBP              AUS  PASSED        1963      GB     False
1  20100a1d-12bc-41ed-a5e1-bc46216e9696  CARD_PAYMENT     588      GBP               CA  PASSED        1988      GB     False
2  0fe472c9-cf3e-4e43-90f3-a0cfb6a4f1f0  CARD_PAYMENT    1264      GBP              UKR  PASSED        1977      GB     False
3  20100a1d-12bc-41ed-a5e1-bc46216e9696  CARD_PAYMENT      66      GBP               CA  PASSED        1988      GB     False
4  821014c5-af06-40ff-91f4-77fe7667809f  CARD_PAYMENT     968      GBP              NZL  FAILED        1992      GB     False

#### Treat Country Columns

##### All

In [343]:
# Import ISO country code table

country_codes = pd.read_excel("CountryCodesTable_ISO3166.xlsx")
country_codes["Numeric_3"] = (
    country_codes["Numeric"]
    .astype(str)
    .str.strip()
    .str.zfill(3)
)

country_codes.head()

          Country Alpha-2-code Alpha-3-code  Numeric Numeric_3
0     Afghanistan           AF          AFG        4       004
1         Albania           AL          ALB        8       008
2         Algeria           DZ          DZA       12       012
3  American Samoa           AS          ASM       16       016
4         Andorra           AD          AND       20       020

In [344]:
## Creating From/To Dictionary

iso2_to_country_name = dict(
    zip(country_codes["Alpha-2-code"], country_codes["Country"])
)

iso3_to_country_name = dict(
    zip(country_codes["Alpha-3-code"], country_codes["Country"])
)

numeric_to_country_name = dict(
    zip(country_codes["Numeric_3"], country_codes["Country"])
)

manual_country_mapping = {
    "ROM": "Romania",
    "BP0": "Hungary",
    "BP1": "Hungary",
    "BP2": "Hungary",
    "NSW": "New South Wales",
    "FL" : "Liechtenstein"
}

country_depara = {}
country_depara.update(iso2_to_country_name)
country_depara.update(iso3_to_country_name)
country_depara.update(numeric_to_country_name)
country_depara.update(manual_country_mapping)

country_depara

{'AF': 'Afghanistan',
 'AL': 'Albania',
 'DZ': 'Algeria',
 'AS': 'American Samoa',
 'AD': 'Andorra',
 'AO': 'Angola',
 'AI': 'Anguilla',
 'AQ': 'Antarctica',
 'AG': 'Antigua and Barbuda',
 'AR': 'Argentina',
 'AM': 'Armenia',
 'AW': 'Aruba',
 'AU': 'Australia',
 'AT': 'Austria',
 'AZ': 'Azerbaijan',
 'BS': 'Bahamas (the)',
 'BH': 'Bahrain',
 'BD': 'Bangladesh',
 'BB': 'Barbados',
 'BY': 'Belarus',
 'BE': 'Belgium',
 'BZ': 'Belize',
 'BJ': 'Benin',
 'BM': 'Bermuda',
 'BT': 'Bhutan',
 'BO': 'Bolivia (Plurinational State of)',
 'BQ': 'Bonaire, Sint Eustatius and Saba',
 'BA': 'Bosnia and Herzegovina',
 'BW': 'Botswana',
 'BV': 'Bouvet Island',
 'BR': 'Brazil',
 'IO': 'British Indian Ocean Territory (the)',
 'BN': 'Brunei Darussalam',
 'BG': 'Bulgaria',
 'BF': 'Burkina Faso',
 'BI': 'Burundi',
 'CV': 'Cabo Verde',
 'KH': 'Cambodia',
 'CM': 'Cameroon',
 'CA': 'Canada',
 'KY': 'Cayman Islands (the)',
 'CF': 'Central African Republic (the)',
 'TD': 'Chad',
 'CL': 'Chile',
 'CN': 'China',
 'CX': 'Christmas Island',
 'CC': 'Cocos (Keeling) Islands (the)',
 'CO': 'Colombia',
 'KM': 'Comoros (the)',
 'CD': 'Congo (the Democratic Republic of the)',
 'CG': 'Congo (the)',
 'CK': 'Cook Islands (the)',
 'CR': 'Costa Rica',
 'HR': 'Croatia',
 'CU': 'Cuba',
 'CW': 'Curaçao',
 'CY': 'Cyprus',
 'CZ': 'Czechia',
 'CI': "Côte d'Ivoire",
 'DK': 'Denmark',
 'DJ': 'Djibouti',
 'DM': 'Dominica',
 'DO': 'Dominican Republic (the)',
 'EC': 'Ecuador',
 'EG': 'Egypt',
 'SV': 'El Salvador',
 'GQ': 'Equatorial Guinea',
 'ER': 'Eritrea',
 'EE': 'Estonia',
 'SZ': 'Eswatini',
 'ET': 'Ethiopia',
 'FK': 'Falkland Islands (the) [Malvinas]',
 'FO': 'Faroe Islands (the)',
 'FJ': 'Fiji',
 'FI': 'Finland',
 'FR': 'France',
 'GF': 'French Guiana',
 'PF': 'French Polynesia',
 'TF': 'French Southern Territories (the)',
 'GA': 'Gabon',
 'GM': 'Gambia (the)',
 'GE': 'Georgia',
 'DE': 'Germany',
 'GH': 'Ghana',
 'GI': 'Gibraltar',
 'GR': 'Greece',
 'GL': 'Greenland',
 'GD': 'Grenada',
 'GP': 'Guadeloupe',
 'GU': 'Guam',
 'GT': 'Guatemala',
 'GG': 'Guernsey',
 'GN': 'Guinea',
 'GW': 'Guinea-Bissau',
 'GY': 'Guyana',
 'HT': 'Haiti',
 'HM': 'Heard Island and McDonald Islands',
 'VA': 'Holy See (the)',
 'HN': 'Honduras',
 'HK': 'Hong Kong',
 'HU': 'Hungary',
 'IS': 'Iceland',
 'IN': 'India',
 'ID': 'Indonesia',
 'IR': 'Iran (Islamic Republic of)',
 'IQ': 'Iraq',
 'IE': 'Ireland',
 'IM': 'Isle of Man',
 'IL': 'Israel',
 'IT': 'Italy',
 'JM': 'Jamaica',
 'JP': 'Japan',
 'JE': 'Jersey',
 'JO': 'Jordan',
 'KZ': 'Kazakhstan',
 'KE': 'Kenya',
 'KI': 'Kiribati',
 'KP': "Korea (the Democratic People's Republic of)",
 'KR': 'Korea (the Republic of)',
 'KW': 'Kuwait',
 'KG': 'Kyrgyzstan',
 'LA': "Lao People's Democratic Republic (the)",
 'LV': 'Latvia',
 'LB': 'Lebanon',
 'LS': 'Lesotho',
 'LR': 'Liberia',
 'LY': 'Libya',
 'LI': 'Liechtenstein',
 'LT': 'Lithuania',
 'LU': 'Luxembourg',
 'MO': 'Macao',
 'MG': 'Madagascar',
 'MW': 'Malawi',
 'MY': 'Malaysia',
 'MV': 'Maldives',
 'ML': 'Mali',
 'MT': 'Malta',
 'MH': 'Marshall Islands (the)',
 'MQ': 'Martinique',
 'MR': 'Mauritania',
 'MU': 'Mauritius',
 'YT': 'Mayotte',
 'MX': 'Mexico',
 'FM': 'Micronesia (Federated States of)',
 'MD': 'Moldova (the Republic of)',
 'MC': 'Monaco',
 'MN': 'Mongolia',
 'ME': 'Montenegro',
 'MS': 'Montserrat',
 'MA': 'Morocco',
 'MZ': 'Mozambique',
 'MM': 'Myanmar',
 nan: 'Namibia',
 'NR': 'Nauru',
 'NP': 'Nepal',
 'NL': 'Netherlands (the)',
 'NC': 'New Caledonia',
 'NZ': 'New Zealand',
 'NI': 'Nicaragua',
 'NE': 'Niger (the)',
 'NG': 'Nigeria',
 'NU': 'Niue',
 'NF': 'Norfolk Island',
 'MP': 'Northern Mariana Islands (the)',
 'NO': 'Norway',
 'OM': 'Oman',
 'PK': 'Pakistan',
 'PW': 'Palau',
 'PS': 'Palestine, State of',
 'PA': 'Panama',
 'PG': 'Papua New Guinea',
 'PY': 'Paraguay',
 'PE': 'Peru',
 'PH': 'Philippines (the)',
 'PN': 'Pitcairn',
 'PL': 'Poland',
 'PT': 'Portugal',
 'PR': 'Puerto Rico',
 'QA': 'Qatar',
 'MK': 'Republic of North Macedonia',
 'RO': 'Romania',
 'RU': 'Russian Federation (the)',
 'RW': 'Rwanda',
 'RE': 'Réunion',
 'BL': 'Saint Barthélemy',
 'SH': 'Saint Helena, Ascension and Tristan da Cunha',
 'KN': 'Saint Kitts and Nevis',
 'LC': 'Saint Lucia',
 'MF': 'Saint Martin (French part)',
 'PM': 'Saint Pierre and Miquelon',
 'VC': 'Saint Vincent and the Grenadines',
 'WS': 'Samoa',
 'SM': 'San Marino',
 'ST': 'Sao Tome and Principe',
 'SA': 'Saudi Arabia',
 'SN': 'Senegal',
 'RS': 'Serbia',
 'SC': 'Seychelles',
 'SL': 'Sierra Leone',
 'SG': 'Singapore',
 'SX': 'Sint Maarten (Dutch part)',
 'SK': 'Slovakia',
 'SI': 'Slovenia',
 'SB': 'Solomon Islands',
 'SO': 'Somalia',
 'ZA': 'South Africa',
 'GS': 'South Georgia and the South Sandwich Islands',
 'SS': 'South Sudan',
 'ES': 'Spain',
 'LK': 'Sri Lanka',
 'SD': 'Sudan (the)',
 'SR': 'Suriname',
 'SJ': 'Svalbard and Jan Mayen',
 'SE': 'Sweden',
 'CH': 'Switzerland',
 'SY': 'Syrian Arab Republic',
 'TW': 'Taiwan (Province of China)',
 'TJ': 'Tajikistan',
 'TZ': 'Tanzania, United Republic of',
 'TH': 'Thailand',
 'TL': 'Timor-Leste',
 'TG': 'Togo',
 'TK': 'Tokelau',
 'TO': 'Tonga',
 'TT': 'Trinidad and Tobago',
 'TN': 'Tunisia',
 'TR': 'Turkey',
 'TM': 'Turkmenistan',
 'TC': 'Turks and Caicos Islands (the)',
 'TV': 'Tuvalu',
 'UG': 'Uganda',
 'UA': 'Ukraine',
 'AE': 'United Arab Emirates (the)',
 'GB': 'United Kingdom of Great Britain and Northern Ireland (the)',
 'UM': 'United States Minor Outlying Islands (the)',
 'US': 'United States of America (the)',
 'UY': 'Uruguay',
 'UZ': 'Uzbekistan',
 'VU': 'Vanuatu',
 'VE': 'Venezuela (Bolivarian Republic of)',
 'VN': 'Viet Nam',
 'VG': 'Virgin Islands (British)',
 'VI': 'Virgin Islands (U.S.)',
 'WF': 'Wallis and Futuna',
 'EH': 'Western Sahara',
 'YE': 'Yemen',
 'ZM': 'Zambia',
 'ZW': 'Zimbabwe',
 'AX': 'Åland Islands',
 'AFG': 'Afghanistan',
 'ALB': 'Albania',
 'DZA': 'Algeria',
 'ASM': 'American Samoa',
 'AND': 'Andorra',
 'AGO': 'Angola',
 'AIA': 'Anguilla',
 'ATA': 'Antarctica',
 'ATG': 'Antigua and Barbuda',
 'ARG': 'Argentina',
 'ARM': 'Armenia',
 'ABW': 'Aruba',
 'AUS': 'Australia',
 'AUT': 'Austria',
 'AZE': 'Azerbaijan',
 'BHS': 'Bahamas (the)',
 'BHR': 'Bahrain',
 'BGD': 'Bangladesh',
 'BRB': 'Barbados',
 'BLR': 'Belarus',
 'BEL': 'Belgium',
 'BLZ': 'Belize',
 'BEN': 'Benin',
 'BMU': 'Bermuda',
 'BTN': 'Bhutan',
 'BOL': 'Bolivia (Plurinational State of)',
 'BES': 'Bonaire, Sint Eustatius and Saba',
 'BIH': 'Bosnia and Herzegovina',
 'BWA': 'Botswana',
 'BVT': 'Bouvet Island',
 'BRA': 'Brazil',
 'IOT': 'British Indian Ocean Territory (the)',
 'BRN': 'Brunei Darussalam',
 'BGR': 'Bulgaria',
 'BFA': 'Burkina Faso',
 'BDI': 'Burundi',
 'CPV': 'Cabo Verde',
 'KHM': 'Cambodia',
 'CMR': 'Cameroon',
 'CAN': 'Canada',
 'CYM': 'Cayman Islands (the)',
 'CAF': 'Central African Republic (the)',
 'TCD': 'Chad',
 'CHL': 'Chile',
 'CHN': 'China',
 'CXR': 'Christmas Island',
 'CCK': 'Cocos (Keeling) Islands (the)',
 'COL': 'Colombia',
 'COM': 'Comoros (the)',
 'COD': 'Congo (the Democratic Republic of the)',
 'COG': 'Congo (the)',
 'COK': 'Cook Islands (the)',
 'CRI': 'Costa Rica',
 'HRV': 'Croatia',
 'CUB': 'Cuba',
 'CUW': 'Curaçao',
 'CYP': 'Cyprus',
 'CZE': 'Czechia',
 'CIV': "Côte d'Ivoire",
 'DNK': 'Denmark',
 'DJI': 'Djibouti',
 'DMA': 'Dominica',
 'DOM': 'Dominican Republic (the)',
 'ECU': 'Ecuador',
 'EGY': 'Egypt',
 'SLV': 'El Salvador',
 'GNQ': 'Equatorial Guinea',
 'ERI': 'Eritrea',
 'EST': 'Estonia',
 'SWZ': 'Eswatini',
 'ETH': 'Ethiopia',
 'FLK': 'Falkland Islands (the) [Malvinas]',
 'FRO': 'Faroe Islands (the)',
 'FJI': 'Fiji',
 'FIN': 'Finland',
 'FRA': 'France',
 'GUF': 'French Guiana',
 'PYF': 'French Polynesia',
 'ATF': 'French Southern Territories (the)',
 'GAB': 'Gabon',
 'GMB': 'Gambia (the)',
 'GEO': 'Georgia',
 'DEU': 'Germany',
 'GHA': 'Ghana',
 'GIB': 'Gibraltar',
 'GRC': 'Greece',
 'GRL': 'Greenland',
 'GRD': 'Grenada',
 'GLP': 'Guadeloupe',
 'GUM': 'Guam',
 'GTM': 'Guatemala',
 'GGY': 'Guernsey',
 'GIN': 'Guinea',
 'GNB': 'Guinea-Bissau',
 'GUY': 'Guyana',
 'HTI': 'Haiti',
 'HMD': 'Heard Island and McDonald Islands',
 'VAT': 'Holy See (the)',
 'HND': 'Honduras',
 'HKG': 'Hong Kong',
 'HUN': 'Hungary',
 'ISL': 'Iceland',
 'IND': 'India',
 'IDN': 'Indonesia',
 'IRN': 'Iran (Islamic Republic of)',
 'IRQ': 'Iraq',
 'IRL': 'Ireland',
 'IMN': 'Isle of Man',
 'ISR': 'Israel',
 'ITA': 'Italy',
 'JAM': 'Jamaica',
 'JPN': 'Japan',
 'JEY': 'Jersey',
 'JOR': 'Jordan',
 'KAZ': 'Kazakhstan',
 'KEN': 'Kenya',
 'KIR': 'Kiribati',
 'PRK': "Korea (the Democratic People's Republic of)",
 'KOR': 'Korea (the Republic of)',
 'KWT': 'Kuwait',
 'KGZ': 'Kyrgyzstan',
 'LAO': "Lao People's Democratic Republic (the)",
 'LVA': 'Latvia',
 'LBN': 'Lebanon',
 'LSO': 'Lesotho',
 'LBR': 'Liberia',
 'LBY': 'Libya',
 'LIE': 'Liechtenstein',
 'LTU': 'Lithuania',
 'LUX': 'Luxembourg',
 'MAC': 'Macao',
 'MDG': 'Madagascar',
 'MWI': 'Malawi',
 'MYS': 'Malaysia',
 'MDV': 'Maldives',
 'MLI': 'Mali',
 'MLT': 'Malta',
 'MHL': 'Marshall Islands (the)',
 'MTQ': 'Martinique',
 'MRT': 'Mauritania',
 'MUS': 'Mauritius',
 'MYT': 'Mayotte',
 'MEX': 'Mexico',
 'FSM': 'Micronesia (Federated States of)',
 'MDA': 'Moldova (the Republic of)',
 'MCO': 'Monaco',
 'MNG': 'Mongolia',
 'MNE': 'Montenegro',
 'MSR': 'Montserrat',
 'MAR': 'Morocco',
 'MOZ': 'Mozambique',
 'MMR': 'Myanmar',
 'NAM': 'Namibia',
 'NRU': 'Nauru',
 'NPL': 'Nepal',
 'NLD': 'Netherlands (the)',
 'NCL': 'New Caledonia',
 'NZL': 'New Zealand',
 'NIC': 'Nicaragua',
 'NER': 'Niger (the)',
 'NGA': 'Nigeria',
 'NIU': 'Niue',
 'NFK': 'Norfolk Island',
 'MNP': 'Northern Mariana Islands (the)',
 'NOR': 'Norway',
 'OMN': 'Oman',
 'PAK': 'Pakistan',
 'PLW': 'Palau',
 'PSE': 'Palestine, State of',
 'PAN': 'Panama',
 'PNG': 'Papua New Guinea',
 'PRY': 'Paraguay',
 'PER': 'Peru',
 'PHL': 'Philippines (the)',
 'PCN': 'Pitcairn',
 'POL': 'Poland',
 'PRT': 'Portugal',
 'PRI': 'Puerto Rico',
 'QAT': 'Qatar',
 'MKD': 'Republic of North Macedonia',
 'ROU': 'Romania',
 'RUS': 'Russian Federation (the)',
 'RWA': 'Rwanda',
 'REU': 'Réunion',
 'BLM': 'Saint Barthélemy',
 'SHN': 'Saint Helena, Ascension and Tristan da Cunha',
 'KNA': 'Saint Kitts and Nevis',
 'LCA': 'Saint Lucia',
 'MAF': 'Saint Martin (French part)',
 'SPM': 'Saint Pierre and Miquelon',
 'VCT': 'Saint Vincent and the Grenadines',
 'WSM': 'Samoa',
 'SMR': 'San Marino',
 'STP': 'Sao Tome and Principe',
 'SAU': 'Saudi Arabia',
 'SEN': 'Senegal',
 'SRB': 'Serbia',
 'SYC': 'Seychelles',
 'SLE': 'Sierra Leone',
 'SGP': 'Singapore',
 'SXM': 'Sint Maarten (Dutch part)',
 'SVK': 'Slovakia',
 'SVN': 'Slovenia',
 'SLB': 'Solomon Islands',
 'SOM': 'Somalia',
 'ZAF': 'South Africa',
 'SGS': 'South Georgia and the South Sandwich Islands',
 'SSD': 'South Sudan',
 'ESP': 'Spain',
 'LKA': 'Sri Lanka',
 'SDN': 'Sudan (the)',
 'SUR': 'Suriname',
 'SJM': 'Svalbard and Jan Mayen',
 'SWE': 'Sweden',
 'CHE': 'Switzerland',
 'SYR': 'Syrian Arab Republic',
 'TWN': 'Taiwan (Province of China)',
 'TJK': 'Tajikistan',
 'TZA': 'Tanzania, United Republic of',
 'THA': 'Thailand',
 'TLS': 'Timor-Leste',
 'TGO': 'Togo',
 'TKL': 'Tokelau',
 'TON': 'Tonga',
 'TTO': 'Trinidad and Tobago',
 'TUN': 'Tunisia',
 'TUR': 'Turkey',
 'TKM': 'Turkmenistan',
 'TCA': 'Turks and Caicos Islands (the)',
 'TUV': 'Tuvalu',
 'UGA': 'Uganda',
 'UKR': 'Ukraine',
 'ARE': 'United Arab Emirates (the)',
 'GBR': 'United Kingdom of Great Britain and Northern Ireland (the)',
 'UMI': 'United States Minor Outlying Islands (the)',
 'USA': 'United States of America (the)',
 'URY': 'Uruguay',
 'UZB': 'Uzbekistan',
 'VUT': 'Vanuatu',
 'VEN': 'Venezuela (Bolivarian Republic of)',
 'VNM': 'Viet Nam',
 'VGB': 'Virgin Islands (British)',
 'VIR': 'Virgin Islands (U.S.)',
 'WLF': 'Wallis and Futuna',
 'ESH': 'Western Sahara',
 'YEM': 'Yemen',
 'ZMB': 'Zambia',
 'ZWE': 'Zimbabwe',
 'ALA': 'Åland Islands',
 '004': 'Afghanistan',
 '008': 'Albania',
 '012': 'Algeria',
 '016': 'American Samoa',
 '020': 'Andorra',
 '024': 'Angola',
 '660': 'Anguilla',
 '010': 'Antarctica',
 '028': 'Antigua and Barbuda',
 '032': 'Argentina',
 '051': 'Armenia',
 '533': 'Aruba',
 '036': 'Australia',
 '040': 'Austria',
 '031': 'Azerbaijan',
 '044': 'Bahamas (the)',
 '048': 'Bahrain',
 '050': 'Bangladesh',
 '052': 'Barbados',
 '112': 'Belarus',
 '056': 'Belgium',
 '084': 'Belize',
 '204': 'Benin',
 '060': 'Bermuda',
 '064': 'Bhutan',
 '068': 'Bolivia (Plurinational State of)',
 '535': 'Bonaire, Sint Eustatius and Saba',
 '070': 'Bosnia and Herzegovina',
 '072': 'Botswana',
 '074': 'Bouvet Island',
 '076': 'Brazil',
 '086': 'British Indian Ocean Territory (the)',
 '096': 'Brunei Darussalam',
 '100': 'Bulgaria',
 '854': 'Burkina Faso',
 '108': 'Burundi',
 '132': 'Cabo Verde',
 '116': 'Cambodia',
 '120': 'Cameroon',
 '124': 'Canada',
 '136': 'Cayman Islands (the)',
 '140': 'Central African Republic (the)',
 '148': 'Chad',
 '152': 'Chile',
 '156': 'China',
 '162': 'Christmas Island',
 '166': 'Cocos (Keeling) Islands (the)',
 '170': 'Colombia',
 '174': 'Comoros (the)',
 '180': 'Congo (the Democratic Republic of the)',
 '178': 'Congo (the)',
 '184': 'Cook Islands (the)',
 '188': 'Costa Rica',
 '191': 'Croatia',
 '192': 'Cuba',
 '531': 'Curaçao',
 '196': 'Cyprus',
 '203': 'Czechia',
 '384': "Côte d'Ivoire",
 '208': 'Denmark',
 '262': 'Djibouti',
 '212': 'Dominica',
 '214': 'Dominican Republic (the)',
 '218': 'Ecuador',
 '818': 'Egypt',
 '222': 'El Salvador',
 '226': 'Equatorial Guinea',
 '232': 'Eritrea',
 '233': 'Estonia',
 '748': 'Eswatini',
 '231': 'Ethiopia',
 '238': 'Falkland Islands (the) [Malvinas]',
 '234': 'Faroe Islands (the)',
 '242': 'Fiji',
 '246': 'Finland',
 '250': 'France',
 '254': 'French Guiana',
 '258': 'French Polynesia',
 '260': 'French Southern Territories (the)',
 '266': 'Gabon',
 '270': 'Gambia (the)',
 '268': 'Georgia',
 '276': 'Germany',
 '288': 'Ghana',
 '292': 'Gibraltar',
 '300': 'Greece',
 '304': 'Greenland',
 '308': 'Grenada',
 '312': 'Guadeloupe',
 '316': 'Guam',
 '320': 'Guatemala',
 '831': 'Guernsey',
 '324': 'Guinea',
 '624': 'Guinea-Bissau',
 '328': 'Guyana',
 '332': 'Haiti',
 '334': 'Heard Island and McDonald Islands',
 '336': 'Holy See (the)',
 '340': 'Honduras',
 '344': 'Hong Kong',
 '348': 'Hungary',
 '352': 'Iceland',
 '356': 'India',
 '360': 'Indonesia',
 '364': 'Iran (Islamic Republic of)',
 '368': 'Iraq',
 '372': 'Ireland',
 '833': 'Isle of Man',
 '376': 'Israel',
 '380': 'Italy',
 '388': 'Jamaica',
 '392': 'Japan',
 '832': 'Jersey',
 '400': 'Jordan',
 '398': 'Kazakhstan',
 '404': 'Kenya',
 '296': 'Kiribati',
 '408': "Korea (the Democratic People's Republic of)",
 '410': 'Korea (the Republic of)',
 '414': 'Kuwait',
 '417': 'Kyrgyzstan',
 '418': "Lao People's Democratic Republic (the)",
 '428': 'Latvia',
 '422': 'Lebanon',
 '426': 'Lesotho',
 '430': 'Liberia',
 '434': 'Libya',
 '438': 'Liechtenstein',
 '440': 'Lithuania',
 '442': 'Luxembourg',
 '446': 'Macao',
 '450': 'Madagascar',
 '454': 'Malawi',
 '458': 'Malaysia',
 '462': 'Maldives',
 '466': 'Mali',
 '470': 'Malta',
 '584': 'Marshall Islands (the)',
 '474': 'Martinique',
 '478': 'Mauritania',
 '480': 'Mauritius',
 '175': 'Mayotte',
 '484': 'Mexico',
 '583': 'Micronesia (Federated States of)',
 '498': 'Moldova (the Republic of)',
 '492': 'Monaco',
 '496': 'Mongolia',
 '499': 'Montenegro',
 '500': 'Montserrat',
 '504': 'Morocco',
 '508': 'Mozambique',
 '104': 'Myanmar',
 '516': 'Namibia',
 '520': 'Nauru',
 '524': 'Nepal',
 '528': 'Netherlands (the)',
 '540': 'New Caledonia',
 '554': 'New Zealand',
 '558': 'Nicaragua',
 '562': 'Niger (the)',
 '566': 'Nigeria',
 '570': 'Niue',
 '574': 'Norfolk Island',
 '580': 'Northern Mariana Islands (the)',
 '578': 'Norway',
 '512': 'Oman',
 '586': 'Pakistan',
 '585': 'Palau',
 '275': 'Palestine, State of',
 '591': 'Panama',
 '598': 'Papua New Guinea',
 '600': 'Paraguay',
 '604': 'Peru',
 '608': 'Philippines (the)',
 '612': 'Pitcairn',
 '616': 'Poland',
 '620': 'Portugal',
 '630': 'Puerto Rico',
 '634': 'Qatar',
 '807': 'Republic of North Macedonia',
 '642': 'Romania',
 '643': 'Russian Federation (the)',
 '646': 'Rwanda',
 '638': 'Réunion',
 '652': 'Saint Barthélemy',
 '654': 'Saint Helena, Ascension and Tristan da Cunha',
 '659': 'Saint Kitts and Nevis',
 '662': 'Saint Lucia',
 '663': 'Saint Martin (French part)',
 '666': 'Saint Pierre and Miquelon',
 '670': 'Saint Vincent and the Grenadines',
 '882': 'Samoa',
 '674': 'San Marino',
 '678': 'Sao Tome and Principe',
 '682': 'Saudi Arabia',
 '686': 'Senegal',
 '688': 'Serbia',
 '690': 'Seychelles',
 '694': 'Sierra Leone',
 '702': 'Singapore',
 '534': 'Sint Maarten (Dutch part)',
 '703': 'Slovakia',
 '705': 'Slovenia',
 '090': 'Solomon Islands',
 '706': 'Somalia',
 '710': 'South Africa',
 '239': 'South Georgia and the South Sandwich Islands',
 '728': 'South Sudan',
 '724': 'Spain',
 '144': 'Sri Lanka',
 '729': 'Sudan (the)',
 '740': 'Suriname',
 '744': 'Svalbard and Jan Mayen',
 '752': 'Sweden',
 '756': 'Switzerland',
 '760': 'Syrian Arab Republic',
 '158': 'Taiwan (Province of China)',
 '762': 'Tajikistan',
 '834': 'Tanzania, United Republic of',
 '764': 'Thailand',
 '626': 'Timor-Leste',
 '768': 'Togo',
 '772': 'Tokelau',
 '776': 'Tonga',
 '780': 'Trinidad and Tobago',
 '788': 'Tunisia',
 '792': 'Turkey',
 '795': 'Turkmenistan',
 '796': 'Turks and Caicos Islands (the)',
 '798': 'Tuvalu',
 '800': 'Uganda',
 '804': 'Ukraine',
 '784': 'United Arab Emirates (the)',
 '826': 'United Kingdom of Great Britain and Northern Ireland (the)',
 '581': 'United States Minor Outlying Islands (the)',
 '840': 'United States of America (the)',
 '858': 'Uruguay',
 '860': 'Uzbekistan',
 '548': 'Vanuatu',
 '862': 'Venezuela (Bolivarian Republic of)',
 '704': 'Viet Nam',
 '092': 'Virgin Islands (British)',
 '850': 'Virgin Islands (U.S.)',
 '876': 'Wallis and Futuna',
 '732': 'Western Sahara',
 '887': 'Yemen',
 '894': 'Zambia',
 '716': 'Zimbabwe',
 '248': 'Åland Islands',
 'ROM': 'Romania',
 'BP0': 'Hungary',
 'BP1': 'Hungary',
 'BP2': 'Hungary',
 'NSW': 'New South Wales',
 'FL': 'Liechtenstein'}

##### Country

In [345]:
# Clean COUNTRY
df["COUNTRY_CLEAN"] = (
    df["COUNTRY"]
    .astype(str)
    .str.strip()
    .str.upper()
)

# Apply De/Para to COUNTRY
df["COUNTRY_NAME"] = df["COUNTRY_CLEAN"].map(country_depara)

##### Merchant Country

In [346]:
# ------------------------------------------------------------
# Clean MERCHANT_COUNTRY with safer extraction logic
# ------------------------------------------------------------

# Identify original nulls first
original_null = df["MERCHANT_COUNTRY"].isna()

# Clean text
df["MERCHANT_COUNTRY_CLEAN"] = (
    df["MERCHANT_COUNTRY"]
    .astype("string")
    .str.replace("%20", " ", regex=False)
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
    .str.upper()
)

# Start extracted column as real missing values
df["MERCHANT_COUNTRY_EXTRACTED"] = pd.NA

# 1. BP codes only when the full value is BP + digits
mask_bp = df["MERCHANT_COUNTRY_CLEAN"].str.fullmatch(r"BP\d+", na=False)

df.loc[mask_bp, "MERCHANT_COUNTRY_EXTRACTED"] = df.loc[
    mask_bp, "MERCHANT_COUNTRY_CLEAN"
]

# 2. Numeric ISO only when the full value is numeric
mask_numeric = df["MERCHANT_COUNTRY_CLEAN"].str.fullmatch(r"\d{1,3}", na=False)

df.loc[mask_numeric, "MERCHANT_COUNTRY_EXTRACTED"] = (
    df.loc[mask_numeric, "MERCHANT_COUNTRY_CLEAN"]
    .str.zfill(3)
)

# 3. Alpha country code only when it appears as a final separate token
# Example: "PARIS FRA" -> "FRA"
mask_alpha_final_token = df["MERCHANT_COUNTRY_CLEAN"].str.contains(
    r"(?:^| )[A-Z]{2,3}$",
    na=False,
    regex=True
)

df.loc[mask_alpha_final_token, "MERCHANT_COUNTRY_EXTRACTED"] = (
    df.loc[mask_alpha_final_token, "MERCHANT_COUNTRY_CLEAN"]
    .str.extract(r"(?:^| )([A-Z]{2,3})$")[0]
)

# 4. Apply De/Para mapping
df["MERCHANT_COUNTRY_NAME"] = df["MERCHANT_COUNTRY_EXTRACTED"].map(country_depara)

# 5. Original null merchant country = Online
df.loc[original_null, "MERCHANT_COUNTRY_NAME"] = "Online"

# 6. Not null but not mapped = Other
df.loc[
    (~original_null) & (df["MERCHANT_COUNTRY_NAME"].isna()),
    "MERCHANT_COUNTRY_NAME"
] = "Other"

In [347]:
merchant_country_validation = (
    df.groupby(
        [
            "MERCHANT_COUNTRY",
            "MERCHANT_COUNTRY_CLEAN",
            "MERCHANT_COUNTRY_EXTRACTED",
            "MERCHANT_COUNTRY_NAME"
        ],
        dropna=False
    )
    .size()
    .reset_index(name="rows")
    .sort_values("rows", ascending=False)
)

merchant_country_validation.tail(50)

                                        MERCHANT_COUNTRY MERCHANT_COUNTRY_CLEAN MERCHANT_COUNTRY_EXTRACTED                                       MERCHANT_COUNTRY_NAME  rows
92                                                   482                    482                        482                                                       Other     1
91                                                   480                    480                        480                                                   Mauritius     1
119                                                  ARI                    ARI                        ARI                                                       Other     1
76                                                   350                    350                        350                                                       Other     1
100                                                  660                    660                        660                                                    Anguilla     1
99                                                   655                    655                        655                                                       Other     1
98                                                   643                    643                        643                                    Russian Federation (the)     1
287                                                  OWN                    OWN                        OWN                                                       Other     1
286                                                   ON                     ON                         ON                                                       Other     1
284                                                   OH                     OH                         OH                                                       Other     1
311                    RIS%20%20%20%20%20%20%20%20%20FRA                RIS FRA                        FRA                                                      France     1
61                                                   214                    214                        214                                    Dominican Republic (the)     1
60                         20PHNOM%20PENH%20%20%20%20KHM       20PHNOM PENH KHM                        KHM                                                    Cambodia     1
59                     20BELFAST%20%20%20%20%20%20%20GBR          20BELFAST GBR                        GBR  United Kingdom of Great Britain and Northern Ireland (the)     1
90                                                   469                    469                        469                                                       Other     1
87                                                   450                    450                        450                                                  Madagascar     1
86                                                   417                    417                        417                                                  Kyrgyzstan     1
85                                                   415                    415                        415                                                       Other     1
48                                                   114                    114                        114                                                       Other     1
46                                                   112                    112                        112                                                     Belarus     1
74                                                   340                    340                        340                                                    Honduras     1
73                                                   319                    319                        319                                                       Other     1
72                                                   311                    311                        311                                                       Other     1
71                                                   310                    310                        310                                                       Other     1
70                                                   297                    297                        297                                                       Other     1
68                                                   281                    281                        281                                                       Other     1
66                                                   239                    239                        239                South Georgia and the South Sandwich Islands     1
29                                                   062                    062                        062                                                       Other     1
57                             2016%20%20%20%20%20%20FRA               2016 FRA                        FRA                                                      France     1
56                           201%20%20%20%20%20%20%20CZE                201 CZE                        CZE                                                     Czechia     1
55             20%20%20PARIS%207%20%20%20%20%20%20%20FRA         20 PARIS 7 FRA                        FRA                                                      France     1
53                                                   185                    185                        185                                                       Other     1
51                                                   173                    173                        173                                                       Other     1
50                                                   16I                    16I                        NaN                                                       Other     1
49                                                   140                    140                        140                              Central African Republic (the)     1
333                                                  TOK                    TOK                        TOK                                                       Other     1
42                                                   101                    101                        101                                                       Other     1
41                                       0DE%20SAN%20ESP            0DE SAN ESP                        ESP                                                       Spain     1
40                                                   089                    089                        089                                                       Other     1
33                                                   074                    074                        074                                               Bouvet Island     1
319                                                  SJO                    SJO                        SJO                                                       Other     1
10                                                   005                    005                        005                                                       Other     1
359                                                  ZHE                    ZHE                        ZHE                                                       Other     1
355                                                  W71                    W71                        NaN                                                       Other     1
16                                                   013                    013                        013                                                       Other     1
15                                                   011                    011                        011                                                       Other     1
2                                          %20-07A%20EGY               -07A EGY                        EGY                                                       Egypt     1
13                                                   008                    008                        008                                                     Albania     1
1              %20%20PARIS%20%20%20%20%20%20%20%20%20FRA              PARIS FRA                        FRA                                                      France     1
0    %20%20%20%20%20%20SERRIS%20%20%20%20%20%20%20%20FRA             SERRIS FRA                        FRA                                                      France     1

In [348]:
columns_to_drop = [
    "COUNTRY",
    "COUNTRY_CLEAN",
    "MERCHANT_COUNTRY",
    "MERCHANT_COUNTRY_CLEAN",
    "MERCHANT_COUNTRY_EXTRACTED"
]

df = df.drop(columns=columns_to_drop, errors="ignore")

df.head()

                                USER_ID          TYPE  AMOUNT CURRENCY     KYC  BIRTH_YEAR  IS_FRAUD                                                COUNTRY_NAME MERCHANT_COUNTRY_NAME
0  7285c1ec-31d0-4022-b311-0ad9227ef7f4  CARD_PAYMENT    3738      GBP  PASSED        1963     False  United Kingdom of Great Britain and Northern Ireland (the)             Australia
1  20100a1d-12bc-41ed-a5e1-bc46216e9696  CARD_PAYMENT     588      GBP  PASSED        1988     False  United Kingdom of Great Britain and Northern Ireland (the)                Canada
2  0fe472c9-cf3e-4e43-90f3-a0cfb6a4f1f0  CARD_PAYMENT    1264      GBP  PASSED        1977     False  United Kingdom of Great Britain and Northern Ireland (the)               Ukraine
3  20100a1d-12bc-41ed-a5e1-bc46216e9696  CARD_PAYMENT      66      GBP  PASSED        1988     False  United Kingdom of Great Britain and Northern Ireland (the)                Canada
4  821014c5-af06-40ff-91f4-77fe7667809f  CARD_PAYMENT     968      GBP  FAILED        1992     False  United Kingdom of Great Britain and Northern Ireland (the)           New Zealand

##### Currency Country

In [349]:
# ============================================================
# Currency-country consistency validation
# ============================================================

import numpy as np
import pandas as pd

# ------------------------------------------------------------
# 1. Currency to country / region mapping
# ------------------------------------------------------------

currency_country_map = {
    # Major single-country currencies
    "GBP": "United Kingdom of Great Britain and Northern Ireland (the)",
    "USD": "United States of America (the)",
    "JPY": "Japan",
    "CHF": "Switzerland",
    "NOK": "Norway",
    "SEK": "Sweden",
    "DKK": "Denmark",
    "PLN": "Poland",
    "CZK": "Czechia",
    "HUF": "Hungary",
    "RON": "Romania",
    "TRY": "Turkey",
    "AUD": "Australia",
    "CAD": "Canada",
    "HKD": "Hong Kong",
    "ILS": "Israel",
    "INR": "India",
    "NZD": "New Zealand",
    "SGD": "Singapore",
    "THB": "Thailand",
    "ZAR": "South Africa",
    "AED": "United Arab Emirates (the)",
    "QAR": "Qatar",
    "MAD": "Morocco",

    # Euro is multi-country
    "EUR": "Eurozone",

    # Crypto is not country-based
    "BTC": "Crypto",
    "ETH": "Crypto",
    "LTC": "Crypto",
    "XRP": "Crypto"
}

eurozone_countries = [
    "Austria",
    "Belgium",
    "Croatia",
    "Cyprus",
    "Estonia",
    "Finland",
    "France",
    "Germany",
    "Greece",
    "Ireland",
    "Italy",
    "Latvia",
    "Lithuania",
    "Luxembourg",
    "Malta",
    "Netherlands (the)",
    "Portugal",
    "Slovakia",
    "Slovenia",
    "Spain"
]

crypto_currencies = ["BTC", "ETH", "LTC", "XRP"]

# ------------------------------------------------------------
# 2. Create currency country / region column
# ------------------------------------------------------------

df["CURRENCY_COUNTRY_NAME"] = df["CURRENCY"].map(currency_country_map)

df.head()

                                USER_ID          TYPE  AMOUNT CURRENCY     KYC  BIRTH_YEAR  IS_FRAUD                                                COUNTRY_NAME MERCHANT_COUNTRY_NAME                                       CURRENCY_COUNTRY_NAME
0  7285c1ec-31d0-4022-b311-0ad9227ef7f4  CARD_PAYMENT    3738      GBP  PASSED        1963     False  United Kingdom of Great Britain and Northern Ireland (the)             Australia  United Kingdom of Great Britain and Northern Ireland (the)
1  20100a1d-12bc-41ed-a5e1-bc46216e9696  CARD_PAYMENT     588      GBP  PASSED        1988     False  United Kingdom of Great Britain and Northern Ireland (the)                Canada  United Kingdom of Great Britain and Northern Ireland (the)
2  0fe472c9-cf3e-4e43-90f3-a0cfb6a4f1f0  CARD_PAYMENT    1264      GBP  PASSED        1977     False  United Kingdom of Great Britain and Northern Ireland (the)               Ukraine  United Kingdom of Great Britain and Northern Ireland (the)
3  20100a1d-12bc-41ed-a5e1-bc46216e9696  CARD_PAYMENT      66      GBP  PASSED        1988     False  United Kingdom of Great Britain and Northern Ireland (the)                Canada  United Kingdom of Great Britain and Northern Ireland (the)
4  821014c5-af06-40ff-91f4-77fe7667809f  CARD_PAYMENT     968      GBP  FAILED        1992     False  United Kingdom of Great Britain and Northern Ireland (the)           New Zealand  United Kingdom of Great Britain and Northern Ireland (the)

#### Cross-boarder flag

In [350]:
# ============================================================
# 1. Cross-border transaction
# Compare COUNTRY_NAME vs MERCHANT_COUNTRY_NAME
# ============================================================

df["MERCHANT_COUNTRY_COMPARISON"] = (
    df["MERCHANT_COUNTRY_NAME"]
    .fillna("Other")
    .astype(str)
    .str.strip()
)

df["MERCHANT_COUNTRY_COMPARISON"] = np.where(
    df["MERCHANT_COUNTRY_COMPARISON"].isin(["", "Other", "Online", "nan", "NaN", "None"]),
    "Other",
    df["MERCHANT_COUNTRY_COMPARISON"]
)

df["CROSS_BORDER_TRANSACTION"] = np.where(
    df["COUNTRY_NAME"] == df["MERCHANT_COUNTRY_COMPARISON"],
    False,
    True
)

In [351]:
columns_to_drop = [
    "MERCHANT_COUNTRY_COMPARISON"
]

df = df.drop(columns=columns_to_drop, errors="ignore")

df.head()

                                USER_ID          TYPE  AMOUNT CURRENCY     KYC  BIRTH_YEAR  IS_FRAUD                                                COUNTRY_NAME MERCHANT_COUNTRY_NAME                                       CURRENCY_COUNTRY_NAME  CROSS_BORDER_TRANSACTION
0  7285c1ec-31d0-4022-b311-0ad9227ef7f4  CARD_PAYMENT    3738      GBP  PASSED        1963     False  United Kingdom of Great Britain and Northern Ireland (the)             Australia  United Kingdom of Great Britain and Northern Ireland (the)                      True
1  20100a1d-12bc-41ed-a5e1-bc46216e9696  CARD_PAYMENT     588      GBP  PASSED        1988     False  United Kingdom of Great Britain and Northern Ireland (the)                Canada  United Kingdom of Great Britain and Northern Ireland (the)                      True
2  0fe472c9-cf3e-4e43-90f3-a0cfb6a4f1f0  CARD_PAYMENT    1264      GBP  PASSED        1977     False  United Kingdom of Great Britain and Northern Ireland (the)               Ukraine  United Kingdom of Great Britain and Northern Ireland (the)                      True
3  20100a1d-12bc-41ed-a5e1-bc46216e9696  CARD_PAYMENT      66      GBP  PASSED        1988     False  United Kingdom of Great Britain and Northern Ireland (the)                Canada  United Kingdom of Great Britain and Northern Ireland (the)                      True
4  821014c5-af06-40ff-91f4-77fe7667809f  CARD_PAYMENT     968      GBP  FAILED        1992     False  United Kingdom of Great Britain and Northern Ireland (the)           New Zealand  United Kingdom of Great Britain and Northern Ireland (the)                      True

#### Different current transaction

In [352]:
# ============================================================
# 2. Different currency transaction
# Compare COUNTRY_NAME vs CURRENCY_COUNTRY_NAME
# ============================================================

df["CURRENCY_COUNTRY_COMPARISON"] = (
    df["CURRENCY_COUNTRY_NAME"]
    .fillna("Other")
    .astype(str)
    .str.strip()
)

df["CURRENCY_COUNTRY_COMPARISON"] = np.where(
    df["CURRENCY_COUNTRY_COMPARISON"].isin(["", "Other", "Crypto", "nan", "NaN", "None"]),
    "Other",
    df["CURRENCY_COUNTRY_COMPARISON"]
)

df["DIFFERENT_CURRENCY_TRANSACTION"] = np.where(
    df["COUNTRY_NAME"] == df["CURRENCY_COUNTRY_COMPARISON"],
    False,
    True
)

In [353]:
columns_to_drop = [
    "CURRENCY_COUNTRY_COMPARISON"
]

df = df.drop(columns=columns_to_drop, errors="ignore")

df.head()

                                USER_ID          TYPE  AMOUNT CURRENCY     KYC  BIRTH_YEAR  IS_FRAUD                                                COUNTRY_NAME MERCHANT_COUNTRY_NAME                                       CURRENCY_COUNTRY_NAME  CROSS_BORDER_TRANSACTION  DIFFERENT_CURRENCY_TRANSACTION
0  7285c1ec-31d0-4022-b311-0ad9227ef7f4  CARD_PAYMENT    3738      GBP  PASSED        1963     False  United Kingdom of Great Britain and Northern Ireland (the)             Australia  United Kingdom of Great Britain and Northern Ireland (the)                      True                           False
1  20100a1d-12bc-41ed-a5e1-bc46216e9696  CARD_PAYMENT     588      GBP  PASSED        1988     False  United Kingdom of Great Britain and Northern Ireland (the)                Canada  United Kingdom of Great Britain and Northern Ireland (the)                      True                           False
2  0fe472c9-cf3e-4e43-90f3-a0cfb6a4f1f0  CARD_PAYMENT    1264      GBP  PASSED        1977     False  United Kingdom of Great Britain and Northern Ireland (the)               Ukraine  United Kingdom of Great Britain and Northern Ireland (the)                      True                           False
3  20100a1d-12bc-41ed-a5e1-bc46216e9696  CARD_PAYMENT      66      GBP  PASSED        1988     False  United Kingdom of Great Britain and Northern Ireland (the)                Canada  United Kingdom of Great Britain and Northern Ireland (the)                      True                           False
4  821014c5-af06-40ff-91f4-77fe7667809f  CARD_PAYMENT     968      GBP  FAILED        1992     False  United Kingdom of Great Britain and Northern Ireland (the)           New Zealand  United Kingdom of Great Britain and Northern Ireland (the)                      True                           False

#### Treating currency amounts

In [354]:
# ============================================================
# Fixed currency conversion to GBP
# Snapshot around 2026-06-02
# AMOUNT_GBP = AMOUNT * currency_to_gbp_rate
# ============================================================

import pandas as pd
import numpy as np

currency_to_gbp = {
    # Fiat currencies: direct value of 1 unit of currency in GBP
    "GBP": 1.000000,
    "EUR": 0.864793,
    "USD": 0.743269,
    "JPY": 0.004657,
    "CZK": 0.035614,
    "DKK": 0.115876,
    "HUF": 0.002434,
    "PLN": 0.204161,
    "RON": 0.164714,
    "SEK": 0.079890,
    "CHF": 0.945537,
    "NOK": 0.080147,
    "TRY": 0.016174,
    "AUD": 0.532365,
    "CAD": 0.537215,
    "HKD": 0.094807,
    "ILS": 0.263635,
    "INR": 0.007827,
    "NZD": 0.441316,
    "SGD": 0.581314,
    "THB": 0.022798,
    "ZAR": 0.045599,
    "AED": 0.202388,
    "QAR": 0.204195,
    "MAD": 0.080849,

    # Crypto currencies: direct value of 1 coin/token in GBP
    "BTC": 51529.69,
    "ETH": 1465.17,
    "LTC": 37.79,
    "XRP": 0.9393
}

currency_conversion_table_gbp = pd.DataFrame({
    "CURRENCY": list(currency_to_gbp.keys()),
    "currency_to_gbp_rate": list(currency_to_gbp.values())
}).sort_values("CURRENCY").reset_index(drop=True)

currency_conversion_table_gbp

   CURRENCY  currency_to_gbp_rate
0       AED                  0.20
1       AUD                  0.53
2       BTC             51,529.69
3       CAD                  0.54
4       CHF                  0.95
5       CZK                  0.04
6       DKK                  0.12
7       ETH              1,465.17
8       EUR                  0.86
9       GBP                  1.00
10      HKD                  0.09
11      HUF                  0.00
12      ILS                  0.26
13      INR                  0.01
14      JPY                  0.00
15      LTC                 37.79
16      MAD                  0.08
17      NOK                  0.08
18      NZD                  0.44
19      PLN                  0.20
20      QAR                  0.20
21      RON                  0.16
22      SEK                  0.08
23      SGD                  0.58
24      THB                  0.02
25      TRY                  0.02
26      USD                  0.74
27      XRP                  0.94
28      ZAR                  0.05

In [355]:
## Mapping and converting the currency

df["currency_to_gbp_rate"] = df["CURRENCY"].map(currency_to_gbp)

df["AMOUNT_GBP"] = df["AMOUNT"] * df["currency_to_gbp_rate"]

## Creating Fiat or Crypto column
crypto_currencies = ["BTC", "ETH", "LTC", "XRP"]

df["CURRENCY_TYPE"] = np.where(
    df["CURRENCY"].isin(crypto_currencies),
    "CRYPTO",
    "FIAT"
)

df[["CURRENCY", "CURRENCY_TYPE"]].drop_duplicates().sort_values("CURRENCY")

df.head()

                                USER_ID          TYPE  AMOUNT CURRENCY     KYC  BIRTH_YEAR  IS_FRAUD                                                COUNTRY_NAME MERCHANT_COUNTRY_NAME                                       CURRENCY_COUNTRY_NAME  CROSS_BORDER_TRANSACTION  DIFFERENT_CURRENCY_TRANSACTION  currency_to_gbp_rate  AMOUNT_GBP CURRENCY_TYPE
0  7285c1ec-31d0-4022-b311-0ad9227ef7f4  CARD_PAYMENT    3738      GBP  PASSED        1963     False  United Kingdom of Great Britain and Northern Ireland (the)             Australia  United Kingdom of Great Britain and Northern Ireland (the)                      True                           False                  1.00    3,738.00          FIAT
1  20100a1d-12bc-41ed-a5e1-bc46216e9696  CARD_PAYMENT     588      GBP  PASSED        1988     False  United Kingdom of Great Britain and Northern Ireland (the)                Canada  United Kingdom of Great Britain and Northern Ireland (the)                      True                           False                  1.00      588.00          FIAT
2  0fe472c9-cf3e-4e43-90f3-a0cfb6a4f1f0  CARD_PAYMENT    1264      GBP  PASSED        1977     False  United Kingdom of Great Britain and Northern Ireland (the)               Ukraine  United Kingdom of Great Britain and Northern Ireland (the)                      True                           False                  1.00    1,264.00          FIAT
3  20100a1d-12bc-41ed-a5e1-bc46216e9696  CARD_PAYMENT      66      GBP  PASSED        1988     False  United Kingdom of Great Britain and Northern Ireland (the)                Canada  United Kingdom of Great Britain and Northern Ireland (the)                      True                           False                  1.00       66.00          FIAT
4  821014c5-af06-40ff-91f4-77fe7667809f  CARD_PAYMENT     968      GBP  FAILED        1992     False  United Kingdom of Great Britain and Northern Ireland (the)           New Zealand  United Kingdom of Great Britain and Northern Ireland (the)                      True                           False                  1.00      968.00          FIAT

In [356]:
currency_validation = df.groupby("CURRENCY").agg(
    transactions=("USER_ID", "count"),
    original_amount=("AMOUNT", "sum"),
    amount_gbp=("AMOUNT_GBP", "sum"),
    avg_fx_rate=("currency_to_gbp_rate", "mean"),
    min_fx_rate=("currency_to_gbp_rate", "min"),
    max_fx_rate=("currency_to_gbp_rate", "max")
).reset_index()

currency_validation["implied_fx_rate"] = (
    currency_validation["amount_gbp"] /
    currency_validation["original_amount"]
).replace([np.inf, -np.inf], 0).fillna(0)

currency_validation = currency_validation.sort_values(
    "amount_gbp",
    ascending=False
)

currency_validation

   CURRENCY  transactions  original_amount            amount_gbp  avg_fx_rate  min_fx_rate  max_fx_rate  implied_fx_rate
2       BTC           283        468004199 24,116,111,293,168.31    51,529.69    51,529.69    51,529.69        51,529.69
7       ETH           197       1638854181  2,401,199,980,375.77     1,465.17     1,465.17     1,465.17         1,465.17
15      LTC           137       5620383823    212,394,304,671.17        37.79        37.79        37.79            37.79
9       GBP        339091       2874187870      2,874,187,870.00         1.00         1.00         1.00             1.00
27      XRP            38       2525590470      2,372,287,128.47         0.94         0.94         0.94             0.94
8       EUR        264695       2164849186      1,872,146,422.11         0.86         0.86         0.86             0.86
26      USD         31542        365847921        271,923,418.39         0.74         0.74         0.74             0.74
19      PLN         22362        536371138        109,506,067.91         0.20         0.20         0.20             0.20
4       CHF          5761        112040047        105,938,009.92         0.95         0.95         0.95             0.95
21      RON          5837        142754858         23,513,723.68         0.16         0.16         0.16             0.16
17      NOK          2602        187458576         15,024,242.49         0.08         0.08         0.08             0.08
1       AUD          2110         21641492         11,521,172.89         0.53         0.53         0.53             0.53
22      SEK          1579        143890184         11,495,386.80         0.08         0.08         0.08             0.08
6       DKK          1711         93482901         10,832,424.64         0.12         0.12         0.12             0.12
11      HUF          1446       4064440919          9,892,849.20         0.00         0.00         0.00             0.00
3       CAD          1463         16508327          8,868,520.89         0.54         0.54         0.54             0.54
24      THB           690        284472612          6,485,406.61         0.02         0.02         0.02             0.02
12      ILS           522         23297768          6,142,107.07         0.26         0.26         0.26             0.26
5       CZK          1507        158651993          5,650,232.08         0.04         0.04         0.04             0.04
0       AED           847         23713512          4,799,330.27         0.20         0.20         0.20             0.20
18      NZD           717          8633356          3,810,038.14         0.44         0.44         0.44             0.44
28      ZAR          1126         68464936          3,121,932.62         0.05         0.05         0.05             0.05
10      HKD           480         26414996          2,504,326.53         0.09         0.09         0.09             0.09
13      INR           207        246286843          1,927,687.12         0.01         0.01         0.01             0.01
23      SGD           487          2411153          1,401,637.00         0.58         0.58         0.58             0.58
16      MAD           115         11245208            909,163.82         0.08         0.08         0.08             0.08
20      QAR            28          1194597            243,930.73         0.20         0.20         0.20             0.20
25      TRY           338          9981155            161,435.20         0.02         0.02         0.02             0.02
14      JPY           733          6894440             32,107.41         0.00         0.00         0.00             0.00

In [357]:
unmapped_currencies = (
    df.loc[df["currency_to_gbp_rate"].isna(), "CURRENCY"]
    .drop_duplicates()
    .sort_values()
)

print("Unmapped currencies:")
print(unmapped_currencies)

Unmapped currencies:
Series([], Name: CURRENCY, dtype: object)

In [358]:
columns_to_drop = [
    "AMOUNT",
    "currency_to_gbp_rate"
]

df = df.drop(columns=columns_to_drop, errors="ignore")

df.head()

                                USER_ID          TYPE CURRENCY     KYC  BIRTH_YEAR  IS_FRAUD                                                COUNTRY_NAME MERCHANT_COUNTRY_NAME                                       CURRENCY_COUNTRY_NAME  CROSS_BORDER_TRANSACTION  DIFFERENT_CURRENCY_TRANSACTION  AMOUNT_GBP CURRENCY_TYPE
0  7285c1ec-31d0-4022-b311-0ad9227ef7f4  CARD_PAYMENT      GBP  PASSED        1963     False  United Kingdom of Great Britain and Northern Ireland (the)             Australia  United Kingdom of Great Britain and Northern Ireland (the)                      True                           False    3,738.00          FIAT
1  20100a1d-12bc-41ed-a5e1-bc46216e9696  CARD_PAYMENT      GBP  PASSED        1988     False  United Kingdom of Great Britain and Northern Ireland (the)                Canada  United Kingdom of Great Britain and Northern Ireland (the)                      True                           False      588.00          FIAT
2  0fe472c9-cf3e-4e43-90f3-a0cfb6a4f1f0  CARD_PAYMENT      GBP  PASSED        1977     False  United Kingdom of Great Britain and Northern Ireland (the)               Ukraine  United Kingdom of Great Britain and Northern Ireland (the)                      True                           False    1,264.00          FIAT
3  20100a1d-12bc-41ed-a5e1-bc46216e9696  CARD_PAYMENT      GBP  PASSED        1988     False  United Kingdom of Great Britain and Northern Ireland (the)                Canada  United Kingdom of Great Britain and Northern Ireland (the)                      True                           False       66.00          FIAT
4  821014c5-af06-40ff-91f4-77fe7667809f  CARD_PAYMENT      GBP  FAILED        1992     False  United Kingdom of Great Britain and Northern Ireland (the)           New Zealand  United Kingdom of Great Britain and Northern Ireland (the)                      True                           False      968.00          FIAT

#### Creating outlier amount GBP transaction

In [359]:
# Calculate IQR limits for AMOUNT_GBP
q1 = df["AMOUNT_GBP"].quantile(0.20)
q3 = df["AMOUNT_GBP"].quantile(0.80)
iqr = q3 - q1

lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr

# Create outlier flag
df["FLAG_OUTLIER"] = np.where(
    (df["AMOUNT_GBP"] < lower_bound) | 
    (df["AMOUNT_GBP"] > upper_bound),
    True,
    False
)

print(f"Q1: {q1:,.2f}")
print(f"Q3: {q3:,.2f}")
print(f"IQR: {iqr:,.2f}")
print(f"Lower bound: {lower_bound:,.2f}")
print(f"Upper bound: {upper_bound:,.2f}")

df["FLAG_OUTLIER"].value_counts(dropna=False)

Q1: 290.00
Q3: 5,392.63
IQR: 5,102.63
Lower bound: -7,363.95
Upper bound: 13,046.58

FLAG_OUTLIER
False    620444
True      68207
Name: count, dtype: int64

In [360]:
outlier_summary = (
    df.groupby(["CURRENCY_TYPE", "IS_FRAUD"], dropna=False)
    .agg(
        transactions=("USER_ID", "count")
    )
    .reset_index()
)

outlier_summary["pct_total"] = (
    outlier_summary["transactions"] / len(df) * 100
).round(2)

outlier_summary = outlier_summary.sort_values(
    ["CURRENCY_TYPE"]
)

outlier_summary

  CURRENCY_TYPE  IS_FRAUD  transactions  pct_total
0        CRYPTO     False           652       0.09
1        CRYPTO      True             3       0.00
2          FIAT     False        673456      97.79
3          FIAT      True         14540       2.11

In [361]:
df[df["FLAG_OUTLIER"] == True].sort_values(
    "AMOUNT_GBP",
    ascending=False
).head(50)

                                     USER_ID          TYPE CURRENCY     KYC  BIRTH_YEAR  IS_FRAUD                                                COUNTRY_NAME                                       MERCHANT_COUNTRY_NAME CURRENCY_COUNTRY_NAME  CROSS_BORDER_TRANSACTION  DIFFERENT_CURRENCY_TRANSACTION            AMOUNT_GBP CURRENCY_TYPE  FLAG_OUTLIER
359878  e908e675-7c4c-41a0-9c2d-b903a1a74c8a           P2P      BTC  PASSED        1986     False                                                      Cyprus                                                      Online                Crypto                      True                            True 10,305,938,000,000.00        CRYPTO          True
496823  d2492abc-1b91-4fc4-aed2-2bcbd06319aa           P2P      BTC  PASSED        1982     False                                                      Latvia                                                      Online                Crypto                      True                            True  5,152,969,000,000.00        CRYPTO          True
576573  3266d82b-2f97-474a-a581-c9425a6383d7  CARD_PAYMENT      BTC  PASSED        1983     False                                                      France  United Kingdom of Great Britain and Northern Ireland (the)                Crypto                      True                            True    673,093,590,143.12        CRYPTO          True
493796  3fc813b5-39dc-4780-bd4f-bd7f9c6fdb5b  CARD_PAYMENT      BTC  PASSED        1993     False  United Kingdom of Great Britain and Northern Ireland (the)  United Kingdom of Great Britain and Northern Ireland (the)                Crypto                     False                            True    277,804,236,713.81        CRYPTO          True
360850  605452f6-e9ce-42ef-bbf4-71e47958dcee  CARD_PAYMENT      BTC  PASSED        1990     False  United Kingdom of Great Britain and Northern Ireland (the)  United Kingdom of Great Britain and Northern Ireland (the)                Crypto                     False                            True    254,693,737,575.40        CRYPTO          True
623159  189b675b-b6cf-4375-b906-058d8dd0eb68  CARD_PAYMENT      BTC  PASSED        1983     False                                                 Switzerland  United Kingdom of Great Britain and Northern Ireland (the)                Crypto                      True                            True    239,439,558,033.77        CRYPTO          True
623197  189b675b-b6cf-4375-b906-058d8dd0eb68  CARD_PAYMENT      BTC  PASSED        1983     False                                                 Switzerland  United Kingdom of Great Britain and Northern Ireland (the)                Crypto                      True                            True    239,425,438,898.71        CRYPTO          True
368549  605452f6-e9ce-42ef-bbf4-71e47958dcee  CARD_PAYMENT      BTC  PASSED        1990     False  United Kingdom of Great Britain and Northern Ireland (the)                                                      Poland                Crypto                      True                            True    203,087,835,163.89        CRYPTO          True
493795  3fc813b5-39dc-4780-bd4f-bd7f9c6fdb5b  CARD_PAYMENT      BTC  PASSED        1993     False  United Kingdom of Great Britain and Northern Ireland (the)  United Kingdom of Great Britain and Northern Ireland (the)                Crypto                     False                            True    185,217,235,612.51        CRYPTO          True
368789  605452f6-e9ce-42ef-bbf4-71e47958dcee  CARD_PAYMENT      BTC  PASSED        1990     False  United Kingdom of Great Britain and Northern Ireland (the)  United Kingdom of Great Britain and Northern Ireland (the)                Crypto                     False                            True    175,681,202,710.80        CRYPTO          True
368765  605452f6-e9ce-42ef-bbf4-71e47958dcee  CARD_PAYMENT      BTC  PASSED        1990     False  United Kingdom of Great Britain and Northern Ireland (the)  United Kingdom of Great Britain and Northern Ireland (the)                Crypto                     False                            True    175,440,301,410.05        CRYPTO          True
370128  605452f6-e9ce-42ef-bbf4-71e47958dcee  CARD_PAYMENT      BTC  PASSED        1990     False  United Kingdom of Great Britain and Northern Ireland (the)                                                     Denmark                Crypto                      True                            True    147,956,374,421.96        CRYPTO          True
316854  605452f6-e9ce-42ef-bbf4-71e47958dcee  CARD_PAYMENT      BTC  PASSED        1990     False  United Kingdom of Great Britain and Northern Ireland (the)  United Kingdom of Great Britain and Northern Ireland (the)                Crypto                     False                            True    147,609,115,841.05        CRYPTO          True
337200  4119acf7-fa29-4817-9a15-7f5c5e8e7fde  CARD_PAYMENT      BTC  PASSED        1993     False                                                     Iceland                              United States of America (the)                Crypto                      True                            True    144,002,810,486.40        CRYPTO          True
263715  750fb39f-7e79-4e06-a53a-c6f8227d4da9           P2P      BTC  PASSED        1987     False  United Kingdom of Great Britain and Northern Ireland (the)                                                      Online                Crypto                      True                            True    120,648,782,033.05        CRYPTO          True
375207  605452f6-e9ce-42ef-bbf4-71e47958dcee  CARD_PAYMENT      BTC  PASSED        1990     False  United Kingdom of Great Britain and Northern Ireland (the)  United Kingdom of Great Britain and Northern Ireland (the)                Crypto                     False                            True    120,157,961,735.80        CRYPTO          True
346959  605452f6-e9ce-42ef-bbf4-71e47958dcee  CARD_PAYMENT      BTC  PASSED        1990     False  United Kingdom of Great Britain and Northern Ireland (the)                                           Netherlands (the)                Crypto                      True                            True    118,493,140,511.28        CRYPTO          True
346958  605452f6-e9ce-42ef-bbf4-71e47958dcee  CARD_PAYMENT      BTC  PASSED        1990     False  United Kingdom of Great Britain and Northern Ireland (the)                                           Netherlands (the)                Crypto                      True                            True    118,493,140,511.28        CRYPTO          True
346960  605452f6-e9ce-42ef-bbf4-71e47958dcee  CARD_PAYMENT      BTC  PASSED        1990     False  United Kingdom of Great Britain and Northern Ireland (the)                                           Netherlands (the)                Crypto                      True                            True    118,491,388,501.82        CRYPTO          True
346961  605452f6-e9ce-42ef-bbf4-71e47958dcee  CARD_PAYMENT      BTC  PASSED        1990     False  United Kingdom of Great Britain and Northern Ireland (the)                                           Netherlands (the)                Crypto                      True                            True    118,473,971,466.60        CRYPTO          True
346968  605452f6-e9ce-42ef-bbf4-71e47958dcee  CARD_PAYMENT      BTC  PASSED        1990     False  United Kingdom of Great Britain and Northern Ireland (the)                                           Netherlands (the)                Crypto                      True                            True    118,321,082,876.37        CRYPTO          True
346966  605452f6-e9ce-42ef-bbf4-71e47958dcee  CARD_PAYMENT      BTC  PASSED        1990     False  United Kingdom of Great Britain and Northern Ireland (the)                                           Netherlands (the)                Crypto                      True                            True    118,321,082,876.37        CRYPTO          True
346967  605452f6-e9ce-42ef-bbf4-71e47958dcee  CARD_PAYMENT      BTC  PASSED        1990     False  United Kingdom of Great Britain and Northern Ireland (the)                                           Netherlands (the)                Crypto                      True                            True    118,321,082,876.37        CRYPTO          True
346969  605452f6-e9ce-42ef-bbf4-71e47958dcee  CARD_PAYMENT      BTC  PASSED        1990     False  United Kingdom of Great Britain and Northern Ireland (the)                                           Netherlands (the)                Crypto                      True                            True    118,321,082,876.37        CRYPTO          True
346970  605452f6-e9ce-42ef-bbf4-71e47958dcee  CARD_PAYMENT      BTC  PASSED        1990     False  United Kingdom of Great Britain and Northern Ireland (the)                                           Netherlands (the)                Crypto                      True                            True    118,316,960,501.17        CRYPTO          True
346971  605452f6-e9ce-42ef-bbf4-71e47958dcee  CARD_PAYMENT      BTC  PASSED        1990     False  United Kingdom of Great Britain and Northern Ireland (the)                                           Netherlands (the)                Crypto                      True                            True    118,316,960,501.17        CRYPTO          True
346940  605452f6-e9ce-42ef-bbf4-71e47958dcee  CARD_PAYMENT      BTC  PASSED        1990     False  United Kingdom of Great Britain and Northern Ireland (the)                                           Netherlands (the)                Crypto                      True                            True    118,260,226,312.48        CRYPTO          True
346945  605452f6-e9ce-42ef-bbf4-71e47958dcee  CARD_PAYMENT      BTC  PASSED        1990     False  United Kingdom of Great Britain and Northern Ireland (the)                                           Netherlands (the)                Crypto                      True                            True    118,259,762,545.27        CRYPTO          True
346942  605452f6-e9ce-42ef-bbf4-71e47958dcee  CARD_PAYMENT      BTC  PASSED        1990     False  United Kingdom of Great Britain and Northern Ireland (the)                                           Netherlands (the)                Crypto                      True                            True    118,259,556,426.51        CRYPTO          True
346941  605452f6-e9ce-42ef-bbf4-71e47958dcee  CARD_PAYMENT      BTC  PASSED        1990     False  United Kingdom of Great Britain and Northern Ireland (the)                                           Netherlands (the)                Crypto                      True                            True    118,259,556,426.51        CRYPTO          True
346944  605452f6-e9ce-42ef-bbf4-71e47958dcee  CARD_PAYMENT      BTC  PASSED        1990     False  United Kingdom of Great Britain and Northern Ireland (the)                                           Netherlands (the)                Crypto                      True                            True    118,258,886,540.54        CRYPTO          True
346943  605452f6-e9ce-42ef-bbf4-71e47958dcee  CARD_PAYMENT      BTC  PASSED        1990     False  United Kingdom of Great Britain and Northern Ireland (the)                                           Netherlands (the)                Crypto                      True                            True    118,258,886,540.54        CRYPTO          True
263713  750fb39f-7e79-4e06-a53a-c6f8227d4da9           P2P      ETH  PASSED        1987     False  United Kingdom of Great Britain and Northern Ireland (the)                                                      Online                Crypto                      True                            True    105,489,790,235.76        CRYPTO          True
332218  1e3ad24b-8818-4db9-82fb-a0c30fc5b35a  CARD_PAYMENT      ETH  PASSED        1969     False  United Kingdom of Great Britain and Northern Ireland (the)                                                      France                Crypto                      True                            True    102,516,721,483.05        CRYPTO          True
298518  39b3f889-bbdd-4d66-93fe-dd75bef27dbf  CARD_PAYMENT      BTC  PASSED        1964     False  United Kingdom of Great Britain and Northern Ireland (the)  United Kingdom of Great Britain and Northern Ireland (the)                Crypto                     False                            True     94,753,051,620.45        CRYPTO          True
297933  73468b9c-f166-4291-9516-af9863602038  CARD_PAYMENT      BTC  PASSED        1981     False                                                      France                              United States of America (the)                Crypto                      True                            True     94,260,994,610.64        CRYPTO          True
297936  73468b9c-f166-4291-9516-af9863602038  CARD_PAYMENT      BTC  PASSED        1981     False                                                      France                              United States of America (the)                Crypto                      True                            True     94,134,901,459.21        CRYPTO          True
682177  5a343d7d-f5bb-4e87-a9d2-646d9142e036  CARD_PAYMENT      BTC  PASSED        1981     False  United Kingdom of Great Britain and Northern Ireland (the)                                                      France                Crypto                      True                            True     90,307,585,264.15        CRYPTO          True
682208  5a343d7d-f5bb-4e87-a9d2-646d9142e036  CARD_PAYMENT      BTC  PASSED        1981     False  United Kingdom of Great Britain and Northern Ireland (the)                                                      France                Crypto                      True                            True     90,304,493,482.75        CRYPTO          True
305234  4119acf7-fa29-4817-9a15-7f5c5e8e7fde  CARD_PAYMENT      BTC  PASSED        1993     False                                                     Iceland                                                     Czechia                Crypto                      True                            True     81,519,248,164.34        CRYPTO          True
305237  4119acf7-fa29-4817-9a15-7f5c5e8e7fde  CARD_PAYMENT      BTC  PASSED        1993     False                                                     Iceland                                                     Czechia                Crypto                      True                            True     81,342,089,090.12        CRYPTO          True
292649  39b3f889-bbdd-4d66-93fe-dd75bef27dbf  CARD_PAYMENT      BTC  PASSED        1964     False  United Kingdom of Great Britain and Northern Ireland (the)  United Kingdom of Great Britain and Northern Ireland (the)                Crypto                     False                            True     76,320,881,507.45        CRYPTO          True
505899  e9972827-7ee9-4ab0-822d-cc06a051e981           P2P      BTC  PASSED        1991     False  United Kingdom of Great Britain and Northern Ireland (the)                                                      Online                Crypto                      True                            True     74,165,755,282.58        CRYPTO          True
324235  4119acf7-fa29-4817-9a15-7f5c5e8e7fde  CARD_PAYMENT      BTC  PASSED        1993     False                                                     Iceland                                                     Czechia                Crypto                      True                            True     64,416,647,112.72        CRYPTO          True
526806  51c35178-5e6e-490c-b4a0-4b2522e2f548  CARD_PAYMENT      BTC  PASSED        1989     False  United Kingdom of Great Britain and Northern Ireland (the)  United Kingdom of Great Britain and Northern Ireland (the)                Crypto                     False                            True     63,180,965,146.52        CRYPTO          True
340408  605452f6-e9ce-42ef-bbf4-71e47958dcee  CARD_PAYMENT      BTC  PASSED        1990     False  United Kingdom of Great Britain and Northern Ireland (the)                              United States of America (the)                Crypto                      True                            True     61,322,495,346.98        CRYPTO          True
305190  4119acf7-fa29-4817-9a15-7f5c5e8e7fde  CARD_PAYMENT      BTC  PASSED        1993     False                                                     Iceland                              United States of America (the)                Crypto                      True                            True     60,528,165,175.63        CRYPTO          True
332581  1e3ad24b-8818-4db9-82fb-a0c30fc5b35a  CARD_PAYMENT      BTC  PASSED        1969     False  United Kingdom of Great Britain and Northern Ireland (the)                                                       Malta                Crypto                      True                            True     56,093,004,757.33        CRYPTO          True
332582  1e3ad24b-8818-4db9-82fb-a0c30fc5b35a  CARD_PAYMENT      BTC  PASSED        1969     False  United Kingdom of Great Britain and Northern Ireland (the)                                                      France                Crypto                      True                            True     55,986,441,358.41        CRYPTO          True
332580  1e3ad24b-8818-4db9-82fb-a0c30fc5b35a  CARD_PAYMENT      BTC  PASSED        1969     False  United Kingdom of Great Britain and Northern Ireland (the)                                                      France                Crypto                      True                            True     55,986,338,299.03        CRYPTO          True

In [362]:
df.head()

                                USER_ID          TYPE CURRENCY     KYC  BIRTH_YEAR  IS_FRAUD                                                COUNTRY_NAME MERCHANT_COUNTRY_NAME                                       CURRENCY_COUNTRY_NAME  CROSS_BORDER_TRANSACTION  DIFFERENT_CURRENCY_TRANSACTION  AMOUNT_GBP CURRENCY_TYPE  FLAG_OUTLIER
0  7285c1ec-31d0-4022-b311-0ad9227ef7f4  CARD_PAYMENT      GBP  PASSED        1963     False  United Kingdom of Great Britain and Northern Ireland (the)             Australia  United Kingdom of Great Britain and Northern Ireland (the)                      True                           False    3,738.00          FIAT         False
1  20100a1d-12bc-41ed-a5e1-bc46216e9696  CARD_PAYMENT      GBP  PASSED        1988     False  United Kingdom of Great Britain and Northern Ireland (the)                Canada  United Kingdom of Great Britain and Northern Ireland (the)                      True                           False      588.00          FIAT         False
2  0fe472c9-cf3e-4e43-90f3-a0cfb6a4f1f0  CARD_PAYMENT      GBP  PASSED        1977     False  United Kingdom of Great Britain and Northern Ireland (the)               Ukraine  United Kingdom of Great Britain and Northern Ireland (the)                      True                           False    1,264.00          FIAT         False
3  20100a1d-12bc-41ed-a5e1-bc46216e9696  CARD_PAYMENT      GBP  PASSED        1988     False  United Kingdom of Great Britain and Northern Ireland (the)                Canada  United Kingdom of Great Britain and Northern Ireland (the)                      True                           False       66.00          FIAT         False
4  821014c5-af06-40ff-91f4-77fe7667809f  CARD_PAYMENT      GBP  FAILED        1992     False  United Kingdom of Great Britain and Northern Ireland (the)           New Zealand  United Kingdom of Great Britain and Northern Ireland (the)                      True                           False      968.00          FIAT         False

#### Creating count similar values column

In [363]:
# Count transactions with the same AMOUNT_GBP within each USER_ID
df["SAME_AMOUNT_GBP_TX_COUNT_BY_USER"] = (
    df.groupby(["USER_ID", "AMOUNT_GBP"])["USER_ID"]
    .transform("count")
)

# Count transactions with the same AMOUNT_GBP within each USER_ID and TYPE
df["SAME_AMOUNT_GBP_TX_COUNT_BY_USER_TYPE"] = (
    df.groupby(["USER_ID", "TYPE", "AMOUNT_GBP"])["USER_ID"]
    .transform("count")
)

df.head()

                                USER_ID          TYPE CURRENCY     KYC  BIRTH_YEAR  IS_FRAUD                                                COUNTRY_NAME MERCHANT_COUNTRY_NAME                                       CURRENCY_COUNTRY_NAME  CROSS_BORDER_TRANSACTION  DIFFERENT_CURRENCY_TRANSACTION  AMOUNT_GBP CURRENCY_TYPE  FLAG_OUTLIER  SAME_AMOUNT_GBP_TX_COUNT_BY_USER  SAME_AMOUNT_GBP_TX_COUNT_BY_USER_TYPE
0  7285c1ec-31d0-4022-b311-0ad9227ef7f4  CARD_PAYMENT      GBP  PASSED        1963     False  United Kingdom of Great Britain and Northern Ireland (the)             Australia  United Kingdom of Great Britain and Northern Ireland (the)                      True                           False    3,738.00          FIAT         False                                 1                                      1
1  20100a1d-12bc-41ed-a5e1-bc46216e9696  CARD_PAYMENT      GBP  PASSED        1988     False  United Kingdom of Great Britain and Northern Ireland (the)                Canada  United Kingdom of Great Britain and Northern Ireland (the)                      True                           False      588.00          FIAT         False                                 1                                      1
2  0fe472c9-cf3e-4e43-90f3-a0cfb6a4f1f0  CARD_PAYMENT      GBP  PASSED        1977     False  United Kingdom of Great Britain and Northern Ireland (the)               Ukraine  United Kingdom of Great Britain and Northern Ireland (the)                      True                           False    1,264.00          FIAT         False                                 1                                      1
3  20100a1d-12bc-41ed-a5e1-bc46216e9696  CARD_PAYMENT      GBP  PASSED        1988     False  United Kingdom of Great Britain and Northern Ireland (the)                Canada  United Kingdom of Great Britain and Northern Ireland (the)                      True                           False       66.00          FIAT         False                                 1                                      1
4  821014c5-af06-40ff-91f4-77fe7667809f  CARD_PAYMENT      GBP  FAILED        1992     False  United Kingdom of Great Britain and Northern Ireland (the)           New Zealand  United Kingdom of Great Britain and Northern Ireland (the)                      True                           False      968.00          FIAT         False                                 1                                      1

In [364]:
same_amount_validation = (
    df.groupby("SAME_AMOUNT_GBP_TX_COUNT_BY_USER")
    .agg(
        transactions=("USER_ID", "count"),
        unique_users=("USER_ID", "nunique"),
        fraud_transactions=("IS_FRAUD", "sum")
    )
    .reset_index()
    .sort_values("SAME_AMOUNT_GBP_TX_COUNT_BY_USER", ascending=False)
)

same_amount_validation["fraud_rate_pct"] = (
    same_amount_validation["fraud_transactions"] /
    same_amount_validation["transactions"] * 100
).round(2)

same_amount_validation.head()

     SAME_AMOUNT_GBP_TX_COUNT_BY_USER  transactions  unique_users  fraud_transactions  fraud_rate_pct
128                               298           298             1                   0            0.00
127                               279           279             1                   0            0.00
126                               241           241             1                   0            0.00
125                               198           396             2                   0            0.00
124                               187           187             1                   0            0.00

In [365]:
same_amount_type_count_validation = (
    df.groupby("SAME_AMOUNT_GBP_TX_COUNT_BY_USER_TYPE")
    .agg(
        transactions=("USER_ID", "count"),
        unique_users=("USER_ID", "nunique"),
        fraud_transactions=("IS_FRAUD", "sum")
    )
    .reset_index()
    .sort_values("SAME_AMOUNT_GBP_TX_COUNT_BY_USER_TYPE", ascending=False)
)

same_amount_type_count_validation["fraud_rate_pct"] = (
    same_amount_type_count_validation["fraud_transactions"] /
    same_amount_type_count_validation["transactions"] * 100
).round(2)

same_amount_type_count_validation.head()

     SAME_AMOUNT_GBP_TX_COUNT_BY_USER_TYPE  transactions  unique_users  fraud_transactions  fraud_rate_pct
112                                    269           269             1                   0            0.00
111                                    198           198             1                   0            0.00
110                                    193           193             1                   0            0.00
109                                    187           187             1                   0            0.00
108                                    165           165             1                   0            0.00

#### Create Age column

In [366]:
df["AGE"] = 2026 - df["BIRTH_YEAR"]

In [367]:
columns_to_drop = [
    "BIRTH_YEAR"
]

df = df.drop(columns=columns_to_drop, errors="ignore")

df.head()

                                USER_ID          TYPE CURRENCY     KYC  IS_FRAUD                                                COUNTRY_NAME MERCHANT_COUNTRY_NAME                                       CURRENCY_COUNTRY_NAME  CROSS_BORDER_TRANSACTION  DIFFERENT_CURRENCY_TRANSACTION  AMOUNT_GBP CURRENCY_TYPE  FLAG_OUTLIER  SAME_AMOUNT_GBP_TX_COUNT_BY_USER  SAME_AMOUNT_GBP_TX_COUNT_BY_USER_TYPE  AGE
0  7285c1ec-31d0-4022-b311-0ad9227ef7f4  CARD_PAYMENT      GBP  PASSED     False  United Kingdom of Great Britain and Northern Ireland (the)             Australia  United Kingdom of Great Britain and Northern Ireland (the)                      True                           False    3,738.00          FIAT         False                                 1                                      1   63
1  20100a1d-12bc-41ed-a5e1-bc46216e9696  CARD_PAYMENT      GBP  PASSED     False  United Kingdom of Great Britain and Northern Ireland (the)                Canada  United Kingdom of Great Britain and Northern Ireland (the)                      True                           False      588.00          FIAT         False                                 1                                      1   38
2  0fe472c9-cf3e-4e43-90f3-a0cfb6a4f1f0  CARD_PAYMENT      GBP  PASSED     False  United Kingdom of Great Britain and Northern Ireland (the)               Ukraine  United Kingdom of Great Britain and Northern Ireland (the)                      True                           False    1,264.00          FIAT         False                                 1                                      1   49
3  20100a1d-12bc-41ed-a5e1-bc46216e9696  CARD_PAYMENT      GBP  PASSED     False  United Kingdom of Great Britain and Northern Ireland (the)                Canada  United Kingdom of Great Britain and Northern Ireland (the)                      True                           False       66.00          FIAT         False                                 1                                      1   38
4  821014c5-af06-40ff-91f4-77fe7667809f  CARD_PAYMENT      GBP  FAILED     False  United Kingdom of Great Britain and Northern Ireland (the)           New Zealand  United Kingdom of Great Britain and Northern Ireland (the)                      True                           False      968.00          FIAT         False                                 1                                      1   34

#### Final dataset print

In [368]:
df.head(10)

                                USER_ID          TYPE CURRENCY     KYC  IS_FRAUD                                                COUNTRY_NAME                                       MERCHANT_COUNTRY_NAME                                       CURRENCY_COUNTRY_NAME  CROSS_BORDER_TRANSACTION  DIFFERENT_CURRENCY_TRANSACTION  AMOUNT_GBP CURRENCY_TYPE  FLAG_OUTLIER  SAME_AMOUNT_GBP_TX_COUNT_BY_USER  SAME_AMOUNT_GBP_TX_COUNT_BY_USER_TYPE  AGE
0  7285c1ec-31d0-4022-b311-0ad9227ef7f4  CARD_PAYMENT      GBP  PASSED     False  United Kingdom of Great Britain and Northern Ireland (the)                                                   Australia  United Kingdom of Great Britain and Northern Ireland (the)                      True                           False    3,738.00          FIAT         False                                 1                                      1   63
1  20100a1d-12bc-41ed-a5e1-bc46216e9696  CARD_PAYMENT      GBP  PASSED     False  United Kingdom of Great Britain and Northern Ireland (the)                                                      Canada  United Kingdom of Great Britain and Northern Ireland (the)                      True                           False      588.00          FIAT         False                                 1                                      1   38
2  0fe472c9-cf3e-4e43-90f3-a0cfb6a4f1f0  CARD_PAYMENT      GBP  PASSED     False  United Kingdom of Great Britain and Northern Ireland (the)                                                     Ukraine  United Kingdom of Great Britain and Northern Ireland (the)                      True                           False    1,264.00          FIAT         False                                 1                                      1   49
3  20100a1d-12bc-41ed-a5e1-bc46216e9696  CARD_PAYMENT      GBP  PASSED     False  United Kingdom of Great Britain and Northern Ireland (the)                                                      Canada  United Kingdom of Great Britain and Northern Ireland (the)                      True                           False       66.00          FIAT         False                                 1                                      1   38
4  821014c5-af06-40ff-91f4-77fe7667809f  CARD_PAYMENT      GBP  FAILED     False  United Kingdom of Great Britain and Northern Ireland (the)                                                 New Zealand  United Kingdom of Great Britain and Northern Ireland (the)                      True                           False      968.00          FIAT         False                                 1                                      1   34
5  fbe6dfd9-96de-4fde-af16-32e8a0bb7a25  CARD_PAYMENT      GBP    NONE     False  United Kingdom of Great Britain and Northern Ireland (the)                                                      Online  United Kingdom of Great Britain and Northern Ireland (the)                      True                           False    1,641.00          FIAT         False                                 1                                      1   46
6  dd1f6199-127f-49ff-ba25-81393b2e66f2  CARD_PAYMENT      USD  PASSED     False  United Kingdom of Great Britain and Northern Ireland (the)                                               Liechtenstein                              United States of America (the)                      True                            True    4,835.71          FIAT         False                                 1                                      1   50
7  dd1f6199-127f-49ff-ba25-81393b2e66f2  CARD_PAYMENT      USD  PASSED     False  United Kingdom of Great Britain and Northern Ireland (the)                                               Liechtenstein                              United States of America (the)                      True                            True    7,204.51          FIAT         False                                 1                                      1   50
8  20100a1d-12bc-41ed-a5e1-bc46216e9696  CARD_PAYMENT      GBP  PASSED     False  United Kingdom of Great Britain and Northern Ireland (the)  United Kingdom of Great Britain and Northern Ireland (the)  United Kingdom of Great Britain and Northern Ireland (the)                     False                           False      295.00          FIAT         False                                 2                                      2   38
9  1a9e22bd-4cec-47c4-8196-92038ba2e603  CARD_PAYMENT      EUR  PASSED     False                                                      Greece                                                  Luxembourg                                                    Eurozone                      True                            True       76.97          FIAT         False                                 1                                      1   51

## Missions

#### Brief 1

In [397]:
# Step 1: make a TOPUP
step_1_users = set(
    df.loc[
        df["TYPE"] == "TOPUP",
        "USER_ID"
    ].unique()
)

# Step 2: make a TOPUP + KYC PASSED
step_2_users = set(
    df.loc[
        (df["TYPE"] == "TOPUP") &
        (df["KYC"] == "PASSED"),
        "USER_ID"
    ].unique()
)

# Step 3: make a TOPUP + fraud false
step_3_users = set(
    df.loc[
        (df["TYPE"] == "TOPUP") &
        (df["IS_FRAUD"] == False),
        "USER_ID"
    ].unique()
)

# Step 4: make a TOPUP + KYC PASSED + fraud false
step_4_users = set(
    df.loc[
        (df["TYPE"] == "TOPUP") &
        (df["KYC"] == "PASSED") &
        (df["IS_FRAUD"] == False),
        "USER_ID"
    ].unique()
)

# Users with other transaction excluding TOPUP
other_excl_topup_users = set(
    df.loc[
        df["TYPE"] != "TOPUP",
        "USER_ID"
    ].unique()
)

# Users with other transaction excluding TOPUP and ATM
other_excl_topup_atm_users = set(
    df.loc[
        ~df["TYPE"].isin(["TOPUP", "ATM"]),
        "USER_ID"
    ].unique()
)

# Step 5: TOPUP + other transaction excluding TOPUP
step_5_users = step_1_users.intersection(other_excl_topup_users)

# Step 6: TOPUP KYC PASSED + other transaction excluding TOPUP
step_6_users = step_2_users.intersection(other_excl_topup_users)

# Step 7: TOPUP fraud false + other transaction excluding TOPUP
step_7_users = step_3_users.intersection(other_excl_topup_users)

# Step 8: TOPUP KYC PASSED fraud false + other transaction excluding TOPUP
step_8_users = step_4_users.intersection(other_excl_topup_users)

# Step 9: TOPUP + other transaction excluding TOPUP and ATM
step_9_users = step_1_users.intersection(other_excl_topup_atm_users)

# Step 10: TOPUP KYC PASSED + other transaction excluding TOPUP and ATM
step_10_users = step_2_users.intersection(other_excl_topup_atm_users)

# Step 11: TOPUP fraud false + other transaction excluding TOPUP and ATM
step_11_users = step_3_users.intersection(other_excl_topup_atm_users)

# Step 12: TOPUP KYC PASSED fraud false + other transaction excluding TOPUP and ATM
step_12_users = step_4_users.intersection(other_excl_topup_atm_users)

# Summary table
app_conversion_funnel = pd.DataFrame({
    "step": [
        "1. TOPUP",
        "2. TOPUP + KYC PASSED",
        "3. TOPUP + fraud false",
        "4. TOPUP + KYC PASSED + fraud false",
        "5. TOPUP + other transaction excluding TOPUP",
        "6. TOPUP KYC PASSED + other transaction excluding TOPUP",
        "7. TOPUP fraud false + other transaction excluding TOPUP",
        "8. TOPUP KYC PASSED fraud false + other transaction excluding TOPUP",
        "9. TOPUP + other transaction excluding TOPUP and ATM",
        "10. TOPUP KYC PASSED + other transaction excluding TOPUP and ATM",
        "11. TOPUP fraud false + other transaction excluding TOPUP and ATM",
        "12. TOPUP KYC PASSED fraud false + other transaction excluding TOPUP and ATM"
    ],
    "unique_users": [
        len(step_1_users),
        len(step_2_users),
        len(step_3_users),
        len(step_4_users),
        len(step_5_users),
        len(step_6_users),
        len(step_7_users),
        len(step_8_users),
        len(step_9_users),
        len(step_10_users),
        len(step_11_users),
        len(step_12_users)
    ]
})

app_conversion_funnel["conversion_vs_step_1_pct"] = (
    app_conversion_funnel["unique_users"] / len(step_1_users) * 100
).round(2)

pd.set_option("display.max_colwidth", None)
pd.set_option("display.width", 2000)

app_conversion_funnel

                                                                            step  unique_users  conversion_vs_step_1_pct
0                                                                       1. TOPUP          7764                    100.00
1                                                          2. TOPUP + KYC PASSED          6878                     88.59
2                                                         3. TOPUP + fraud false          7465                     96.15
3                                            4. TOPUP + KYC PASSED + fraud false          6618                     85.24
4                                   5. TOPUP + other transaction excluding TOPUP          6394                     82.35
5                        6. TOPUP KYC PASSED + other transaction excluding TOPUP          6139                     79.07
6                       7. TOPUP fraud false + other transaction excluding TOPUP          6102                     78.59
7            8. TOPUP KYC PASSED fraud false + other transaction excluding TOPUP          5885                     75.80
8                           9. TOPUP + other transaction excluding TOPUP and ATM          6311                     81.29
9               10. TOPUP KYC PASSED + other transaction excluding TOPUP and ATM          6068                     78.16
10             11. TOPUP fraud false + other transaction excluding TOPUP and ATM          6023                     77.58
11  12. TOPUP KYC PASSED fraud false + other transaction excluding TOPUP and ATM          5817                     74.92

#### Brief 2

##### Part A

In [247]:
country_rates = df.groupby("COUNTRY_NAME", dropna=False).agg(
    transactions=("USER_ID", "count"),
    users=("USER_ID", "nunique"),
    total_amount=("AMOUNT_GBP", "sum"),
    fraud_transactions=("IS_FRAUD", "sum"),
    fraudster_users=("USER_ID", lambda x: df.loc[x.index][df.loc[x.index, "IS_FRAUD"]]["USER_ID"].nunique()),
    fraud_amount=("AMOUNT_GBP", lambda x: x[df.loc[x.index, "IS_FRAUD"]].sum()),
    kyc_passed_transactions=("KYC", lambda x: (x == "PASSED").sum())
).reset_index()

country_rates["fraud_rate_pct"] = (
    country_rates["fraud_transactions"] / country_rates["transactions"] * 100
).round(2)

country_rates["fraud_user_rate_pct"] = (
    country_rates["fraudster_users"] / country_rates["users"] * 100
).round(2)

country_rates["fraud_amount_rate_pct"] = (
    country_rates["fraud_amount"] / country_rates["total_amount"] * 100
).round(2)

country_rates["kyc_passed_rate_pct"] = (
    country_rates["kyc_passed_transactions"] / country_rates["transactions"] * 100
).round(2)

country_rates = country_rates.sort_values("fraud_amount", ascending=False)

pd.set_option("display.float_format", "{:,.2f}".format)

country_rates[["COUNTRY_NAME", "transactions", "users", "fraudster_users" , "fraud_amount", "fraud_rate_pct", "fraud_user_rate_pct", "fraud_amount_rate_pct"]]

                                                  COUNTRY_NAME  transactions  users  fraudster_users     fraud_amount  fraud_rate_pct  fraud_user_rate_pct  fraud_amount_rate_pct
54  United Kingdom of Great Britain and Northern Ireland (the)        385343   3898              269 2,621,539,437.58            3.40                 6.90                   0.03
49                                                       Spain         19510    298                3     9,471,511.11            0.80                 1.01                   0.01
38                                                      Poland         25725    553                2     8,787,649.22            1.35                 0.36                   0.05
12                                                      France         60184    951                3     3,802,602.81            0.35                 0.32                   0.00
15                                                     Germany          9012    148                1     2,814,923.47            5.64                 0.68                   0.00
42                                                     Romania          6903    155                4     2,257,551.71            0.84                 2.58                   0.00
30                                                   Lithuania         50725    363               14       859,036.29            0.31                 3.86                   0.00
8                                                      Czechia          2265     79                1       138,081.00            0.49                 1.27                   0.00
3                                                      Belgium          2919     57                1       114,060.33            0.14                 1.75                   0.00
35                                           Netherlands (the)          6102     84                1        81,947.59            0.08                 1.19                   0.10
7                                                       Cyprus          4278     36                0             0.00            0.00                 0.00                   0.00
6                                                      Croatia           871     13                0             0.00            0.00                 0.00                   0.00
11                                                     Finland          1302     11                0             0.00            0.00                 0.00                   0.00
10                                                     Estonia          3830     14                0             0.00            0.00                 0.00                   0.00
13                                               French Guiana             8      1                0             0.00            0.00                 0.00                   0.00
14                                                     Georgia             1      1                0             0.00            0.00                 0.00                   0.00
16                                                   Gibraltar          4473     33                0             0.00            0.00                 0.00                   0.00
17                                                      Greece          8458    194                0             0.00            0.00                 0.00                   0.00
5                                                     Colombia             7      1                0             0.00            0.00                 0.00                   0.00
9                                                      Denmark          1910     27                0             0.00            0.00                 0.00                   0.00
4                                                     Bulgaria          1527     37                0             0.00            0.00                 0.00                   0.00
0                                                    Argentina             4      1                0             0.00            0.00                 0.00                   0.00
1                                                      Austria           965     22                0             0.00            0.00                 0.00                   0.00
2                                                      Belarus             2      2                0             0.00            0.00                 0.00                   0.00
23                                                   Indonesia             6      1                0             0.00            0.00                 0.00                   0.00
22                                                     Iceland           103      3                0             0.00            0.00                 0.00                   0.00
21                                                     Hungary          3286     55                0             0.00            0.00                 0.00                   0.00
20                                                   Hong Kong             1      1                0             0.00            0.00                 0.00                   0.00
19                                                    Guernsey           148      3                0             0.00            0.00                 0.00                   0.00
18                                                  Guadeloupe            75      1                0             0.00            0.00                 0.00                   0.00
27                                                      Jersey           626     11                0             0.00            0.00                 0.00                   0.00
24                                                     Ireland         44731    341                0             0.00            0.00                 0.00                   0.00
31                                                  Luxembourg           594      7                0             0.00            0.00                 0.00                   0.00
29                                               Liechtenstein            28      1                0             0.00            0.00                 0.00                   0.00
33                                                       Malta          3632     68                0             0.00            0.00                 0.00                   0.00
32                                                    Maldives           168      1                0             0.00            0.00                 0.00                   0.00
34                                                      Monaco             4      1                0             0.00            0.00                 0.00                   0.00
28                                                      Latvia          8526     63                0             0.00            0.00                 0.00                   0.00
26                                                       Italy          4973     98                0             0.00            0.00                 0.00                   0.00
25                                                 Isle of Man            23      1                0             0.00            0.00                 0.00                   0.00
39                                                    Portugal          8402    108                0             0.00            0.00                 0.00                   0.00
37                                                      Norway          2180     20                0             0.00            0.00                 0.00                   0.00
36                                                 New Zealand            18      1                0             0.00            0.00                 0.00                   0.00
40                                                 Puerto Rico             2      1                0             0.00            0.00                 0.00                   0.00
44                                                     Réunion            19      1                0             0.00            0.00                 0.00                   0.00
45                                                   Singapore            17      1                0             0.00            0.00                 0.00                   0.00
41                                 Republic of North Macedonia             3      1                0             0.00            0.00                 0.00                   0.00
43                                    Russian Federation (the)           737     21                0             0.00            0.00                 0.00                   0.00
47                                                    Slovenia          3034     44                0             0.00            0.00                 0.00                   0.00
46                                                    Slovakia          3280     18                0             0.00            0.00                 0.00                   0.00
50                                                      Sweden          1118     28                0             0.00            0.00                 0.00                   0.00
48                                                South Africa             1      1                0             0.00            0.00                 0.00                   0.00
51                                                 Switzerland          6485    134                0             0.00            0.00                 0.00                   0.00
52                                                      Turkey             4      1                0             0.00            0.00                 0.00                   0.00
53                                                     Ukraine            17      3                0             0.00            0.00                 0.00                   0.00
55                              United States of America (the)            86      3                0             0.00            0.00                 0.00                   0.00

In [95]:
uk_name = "United Kingdom of Great Britain and Northern Ireland (the)"

uk_share_total = pd.DataFrame({
    "metric": [
        "fraud_transactions",
        "fraud_amount",
        "fraudster_users"
    ],
    "uk_value": [
        country_rates.loc[country_rates["COUNTRY_NAME"] == uk_name, "fraud_transactions"].sum(),
        country_rates.loc[country_rates["COUNTRY_NAME"] == uk_name, "fraud_amount"].sum(),
        country_rates.loc[country_rates["COUNTRY_NAME"] == uk_name, "fraudster_users"].sum()
    ],
    "total_value": [
        country_rates["fraud_transactions"].sum(),
        country_rates["fraud_amount"].sum(),
        country_rates["fraudster_users"].sum()
    ]
})

uk_share_total["uk_share_of_total_pct"] = (
    uk_share_total["uk_value"] / uk_share_total["total_value"] * 100
).round(2)

uk_share_total

               metric         uk_value      total_value  uk_share_of_total_pct
0  fraud_transactions        13,088.00        14,543.00                  90.00
1        fraud_amount 2,621,539,437.58 2,649,866,801.11                  98.93
2     fraudster_users           269.00           299.00                  89.97

##### Part B

In [379]:
# ============================================================
# User-level fraud behaviour model
# Target: IS_FRAUD_USER
# Population: KYC PASSED users
# Includes repeated amount features
# ============================================================

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 2000)
pd.set_option("display.max_colwidth", None)
pd.set_option("display.float_format", "{:,.2f}".format)

# ============================================================
# 1. Keep only KYC PASSED population
# Business question: fraudsters who passed KYC
# ============================================================

df_kyc_passed = df[df["KYC"] == "PASSED"].copy()

# ============================================================
# 2. Build user-level dataset
# ============================================================

user_model_df = df_kyc_passed.groupby("USER_ID").agg(
    IS_FRAUD_USER=("IS_FRAUD", "max"),

    AGE=("AGE", "first"),
    COUNTRY_NAME=("COUNTRY_NAME", "first"),

    total_transactions=("USER_ID", "count"),

    avg_amount_gbp=("AMOUNT_GBP", "mean"),
    #median_amount_gbp=("AMOUNT_GBP", "median"),
    #max_amount_gbp=("AMOUNT_GBP", "max"),

    unique_types=("TYPE", "nunique"),
    unique_currencies=("CURRENCY", "nunique"),
    unique_merchant_countries=("MERCHANT_COUNTRY_NAME", "nunique"),

    cross_border_transactions=("CROSS_BORDER_TRANSACTION", "sum"),
    different_currency_transactions=("DIFFERENT_CURRENCY_TRANSACTION", "sum"),
    outlier_transactions=("FLAG_OUTLIER", "sum"),

    #avg_same_amount_count_by_user=("SAME_AMOUNT_GBP_TX_COUNT_BY_USER", "mean"),
    max_same_amount_count_by_user=("SAME_AMOUNT_GBP_TX_COUNT_BY_USER", "max"),
    #median_same_amount_count_by_user=("SAME_AMOUNT_GBP_TX_COUNT_BY_USER", "median"),

    #avg_same_amount_count_by_user_type=("SAME_AMOUNT_GBP_TX_COUNT_BY_USER_TYPE", "mean"),
    max_same_amount_count_by_user_type=("SAME_AMOUNT_GBP_TX_COUNT_BY_USER_TYPE", "max"),
    #median_same_amount_count_by_user_type=("SAME_AMOUNT_GBP_TX_COUNT_BY_USER_TYPE", "median")
).reset_index()

# ============================================================
# 3. Behavioural shares
# ============================================================

user_model_df["cross_border_share"] = (
    user_model_df["cross_border_transactions"] /
    user_model_df["total_transactions"]
)

user_model_df["different_currency_share"] = (
    user_model_df["different_currency_transactions"] /
    user_model_df["total_transactions"]
)

user_model_df["outlier_share"] = (
    user_model_df["outlier_transactions"] /
    user_model_df["total_transactions"]
)

# ============================================================
# 4. Transaction type share per user
# ============================================================

type_share = (
    pd.crosstab(
        df_kyc_passed["USER_ID"],
        df_kyc_passed["TYPE"],
        normalize="index"
    )
    .add_prefix("share_type_")
    .reset_index()
)

user_model_df = user_model_df.merge(
    type_share,
    on="USER_ID",
    how="left"
)

# ============================================================
# 5. Currency share per user
# ============================================================

currency_share = (
    pd.crosstab(
        df_kyc_passed["USER_ID"],
        df_kyc_passed["CURRENCY"],
        normalize="index"
    )
    .add_prefix("share_currency_")
    .reset_index()
)

user_model_df = user_model_df.merge(
    currency_share,
    on="USER_ID",
    how="left"
)

# ============================================================
# 6. Currency type share per user: FIAT vs CRYPTO
# ============================================================

currency_type_share = (
    pd.crosstab(
        df_kyc_passed["USER_ID"],
        df_kyc_passed["CURRENCY_TYPE"],
        normalize="index"
    )
    .add_prefix("share_currency_type_")
    .reset_index()
)

user_model_df = user_model_df.merge(
    currency_type_share,
    on="USER_ID",
    how="left"
)

# Fill missing share columns with zero
user_model_df = user_model_df.fillna(0)

# ============================================================
# 7. Create COUNTRY_SEGMENT: UK vs NON_UK
# ============================================================

uk_country_name = "United Kingdom of Great Britain and Northern Ireland (the)"

user_model_df["COUNTRY_SEGMENT"] = np.where(
    user_model_df["COUNTRY_NAME"] == uk_country_name,
    "UK",
    "NON_UK"
)

# ============================================================
# 8. Define model features
# ============================================================

features_user = [
    "AGE",
    "COUNTRY_NAME",

    # Keep commented to avoid pure volume bias
    # "total_transactions",

    "avg_amount_gbp",
    #"median_amount_gbp",
    #"max_amount_gbp",

    "unique_types",
    "unique_currencies",
    "unique_merchant_countries",

    "cross_border_share",
    "different_currency_share",
    "outlier_share",

    #"avg_same_amount_count_by_user",
    "max_same_amount_count_by_user",
    #"median_same_amount_count_by_user",

    #"avg_same_amount_count_by_user_type",
    "max_same_amount_count_by_user_type",
    #"median_same_amount_count_by_user_type"
] + [
    col for col in user_model_df.columns
    if (
        col.startswith("share_type_") or
        col.startswith("share_currency_") or
        col.startswith("share_currency_type_")
    )
]

# ============================================================
# 9. Function to train one model per country segment
# ============================================================

def train_user_level_model_by_country_segment(segment_name):
    
    segment_df = user_model_df[
        user_model_df["COUNTRY_SEGMENT"] == segment_name
    ].copy()
    
    X_segment = segment_df[features_user]
    y_segment = segment_df["IS_FRAUD_USER"]
    
    print("\n================================================")
    print(f"Country segment: {segment_name}")
    print(f"Users: {segment_df['USER_ID'].nunique()}")
    print(f"Fraudster users: {int(y_segment.sum())}")
    print(f"Fraudster rate: {y_segment.mean() * 100:.2f}%")
    print("================================================")
    
    print("\nTarget distribution:")
    print(y_segment.value_counts(dropna=False))
    
    if y_segment.nunique() < 2:
        print(f"\nSkipping {segment_name}: only one target class available.")
        return None, None, segment_df
    
    min_class_count = y_segment.value_counts().min()
    stratify_target = y_segment if min_class_count >= 2 else None
    
    categorical_features_segment = ["COUNTRY_NAME"]
    
    numeric_features_segment = [
        col for col in features_user
        if col not in categorical_features_segment
    ]
    
    X_train, X_test, y_train, y_test = train_test_split(
        X_segment,
        y_segment,
        test_size=0.30,
        random_state=42,
        stratify=stratify_target
    )
    
    preprocessor_segment = ColumnTransformer(
        transformers=[
            ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features_segment),
            ("num", "passthrough", numeric_features_segment)
        ]
    )
    
    model_segment = DecisionTreeClassifier(
        max_depth=4,
        min_samples_leaf=20,
        class_weight="balanced",
        random_state=42
    )
    
    pipeline_segment = Pipeline(
        steps=[
            ("preprocessor", preprocessor_segment),
            ("model", model_segment)
        ]
    )
    
    pipeline_segment.fit(X_train, y_train)
    
    y_pred = pipeline_segment.predict(X_test)
    y_proba = pipeline_segment.predict_proba(X_test)[:, 1]
    
    print("\nConfusion Matrix:")
    print(confusion_matrix(y_test, y_pred))
    
    print("\nClassification Report:")
    print(classification_report(y_test, y_pred))
    
    print("\nROC AUC:")
    print(roc_auc_score(y_test, y_proba))
    
    encoded_feature_names = pipeline_segment.named_steps["preprocessor"].get_feature_names_out()
    
    feature_importance_segment = pd.DataFrame({
        "country_segment": segment_name,
        "feature": encoded_feature_names,
        "importance": pipeline_segment.named_steps["model"].feature_importances_
    })
    
    feature_importance_segment["importance_pct"] = (
        feature_importance_segment["importance"] * 100
    ).round(2)
    
    feature_importance_segment = feature_importance_segment.sort_values(
        "importance_pct",
        ascending=False
    ).reset_index(drop=True)
    
    return pipeline_segment, feature_importance_segment, segment_df

# ============================================================
# 10. Train UK and NON_UK models
# ============================================================

uk_pipeline, uk_feature_importance, uk_user_model_df = train_user_level_model_by_country_segment("UK")

non_uk_pipeline, non_uk_feature_importance, non_uk_user_model_df = train_user_level_model_by_country_segment("NON_UK")

# ============================================================
# 11. Display feature importance
# ============================================================

print("\nUK feature importance:")
display(uk_feature_importance.head(30))

print("\nNON-UK feature importance:")
display(non_uk_feature_importance.head(30))

================================================
Country segment: UK
Users: 3438
Fraudster users: 231
Fraudster rate: 6.72%
================================================

Target distribution:
IS_FRAUD_USER
False    3207
True      231
Name: count, dtype: int64

Confusion Matrix:
[[831 132]
 [ 27  42]]

Classification Report:
              precision    recall  f1-score   support

       False       0.97      0.86      0.91       963
        True       0.24      0.61      0.35        69

    accuracy                           0.85      1032
   macro avg       0.60      0.74      0.63      1032
weighted avg       0.92      0.85      0.87      1032


ROC AUC:
0.8387286107724954

================================================
Country segment: NON_UK
Users: 3551
Fraudster users: 29
Fraudster rate: 0.82%
================================================

Target distribution:
IS_FRAUD_USER
False    3522
True       29
Name: count, dtype: int64

Confusion Matrix:
[[999  58]
 [  2   7]]

Classification Report:
              precision    recall  f1-score   support

       False       1.00      0.95      0.97      1057
        True       0.11      0.78      0.19         9

    accuracy                           0.94      1066
   macro avg       0.55      0.86      0.58      1066
weighted avg       0.99      0.94      0.96      1066


ROC AUC:
0.8643960895616525

UK feature importance:

   country_segment                                                                       feature  importance  importance_pct
0               UK                                                           num__avg_amount_gbp        0.46           45.74
1               UK                                                       num__share_currency_GBP        0.28           27.68
2               UK                                                 num__share_type_BANK_TRANSFER        0.10            9.81
3               UK                                                            num__outlier_share        0.05            4.87
4               UK                                                  num__share_type_CARD_PAYMENT        0.04            3.64
5               UK                                                       num__cross_border_share        0.03            3.09
6               UK                                                num__unique_merchant_countries        0.03            2.64
7               UK                                                                      num__AGE        0.02            1.71
8               UK                                                       num__share_currency_CHF        0.01            0.82
9               UK                                                             num__unique_types        0.00            0.00
10              UK                                                        num__unique_currencies        0.00            0.00
11              UK                                       num__max_same_amount_count_by_user_type        0.00            0.00
12              UK                                            num__max_same_amount_count_by_user        0.00            0.00
13              UK  cat__COUNTRY_NAME_United Kingdom of Great Britain and Northern Ireland (the)        0.00            0.00
14              UK                                                 num__different_currency_share        0.00            0.00
15              UK                                                           num__share_type_P2P        0.00            0.00
16              UK                                                           num__share_type_ATM        0.00            0.00
17              UK                                                       num__share_currency_AUD        0.00            0.00
18              UK                                                         num__share_type_TOPUP        0.00            0.00
19              UK                                                       num__share_currency_BTC        0.00            0.00
20              UK                                                       num__share_currency_CAD        0.00            0.00
21              UK                                                       num__share_currency_CZK        0.00            0.00
22              UK                                                       num__share_currency_AED        0.00            0.00
23              UK                                                       num__share_currency_DKK        0.00            0.00
24              UK                                                       num__share_currency_ETH        0.00            0.00
25              UK                                                       num__share_currency_EUR        0.00            0.00
26              UK                                                       num__share_currency_HKD        0.00            0.00
27              UK                                                       num__share_currency_HUF        0.00            0.00
28              UK                                                       num__share_currency_ILS        0.00            0.00
29              UK                                                       num__share_currency_INR        0.00            0.00

NON-UK feature importance:

   country_segment                              feature  importance  importance_pct
0           NON_UK              num__share_currency_GBP        0.73           72.77
1           NON_UK                  num__avg_amount_gbp        0.14           13.98
2           NON_UK   num__max_same_amount_count_by_user        0.10           10.01
3           NON_UK                             num__AGE        0.03            3.23
4           NON_UK            cat__COUNTRY_NAME_Austria        0.00            0.00
5           NON_UK            cat__COUNTRY_NAME_Belgium        0.00            0.00
6           NON_UK            cat__COUNTRY_NAME_Denmark        0.00            0.00
7           NON_UK            cat__COUNTRY_NAME_Estonia        0.00            0.00
8           NON_UK            cat__COUNTRY_NAME_Finland        0.00            0.00
9           NON_UK             cat__COUNTRY_NAME_France        0.00            0.00
10          NON_UK            cat__COUNTRY_NAME_Germany        0.00            0.00
11          NON_UK          cat__COUNTRY_NAME_Gibraltar        0.00            0.00
12          NON_UK             cat__COUNTRY_NAME_Greece        0.00            0.00
13          NON_UK           cat__COUNTRY_NAME_Guernsey        0.00            0.00
14          NON_UK            cat__COUNTRY_NAME_Hungary        0.00            0.00
15          NON_UK            cat__COUNTRY_NAME_Iceland        0.00            0.00
16          NON_UK            cat__COUNTRY_NAME_Ireland        0.00            0.00
17          NON_UK        cat__COUNTRY_NAME_Isle of Man        0.00            0.00
18          NON_UK           cat__COUNTRY_NAME_Bulgaria        0.00            0.00
19          NON_UK            cat__COUNTRY_NAME_Croatia        0.00            0.00
20          NON_UK             cat__COUNTRY_NAME_Cyprus        0.00            0.00
21          NON_UK            cat__COUNTRY_NAME_Czechia        0.00            0.00
22          NON_UK      cat__COUNTRY_NAME_Liechtenstein        0.00            0.00
23          NON_UK             cat__COUNTRY_NAME_Latvia        0.00            0.00
24          NON_UK             cat__COUNTRY_NAME_Jersey        0.00            0.00
25          NON_UK              cat__COUNTRY_NAME_Italy        0.00            0.00
26          NON_UK  cat__COUNTRY_NAME_Netherlands (the)        0.00            0.00
27          NON_UK         cat__COUNTRY_NAME_Luxembourg        0.00            0.00
28          NON_UK           cat__COUNTRY_NAME_Maldives        0.00            0.00
29          NON_UK          cat__COUNTRY_NAME_Lithuania        0.00            0.00

In [380]:
# ============================================================
# Business descriptive view by UK / NON_UK segment
# Features selected when importance_pct > 0.01%
# ============================================================

pd.set_option("display.float_format", "{:,.2f}".format)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 2000)
pd.set_option("display.max_colwidth", None)

importance_pct_threshold = 0.01

# ============================================================
# 1. Combine feature importance from UK and NON_UK models
# ============================================================

combined_feature_importance = pd.concat(
    [
        uk_feature_importance.copy(),
        non_uk_feature_importance.copy()
    ],
    ignore_index=True
)

# Clean feature names from pipeline prefixes
combined_feature_importance["clean_feature"] = (
    combined_feature_importance["feature"]
    .str.replace("num__", "", regex=False)
    .str.replace("cat__", "", regex=False)
)

# Keep only features with importance_pct > 0.01%
relevant_features_by_segment = combined_feature_importance[
    combined_feature_importance["importance_pct"] > importance_pct_threshold
].copy()

# ============================================================
# 2. Dictionary with the correct user-level dataframe by segment
# ============================================================

segment_user_model_dfs = {
    "UK": uk_user_model_df.copy(),
    "NON_UK": non_uk_user_model_df.copy()
}

# ============================================================
# 3. Keep only features that exist as direct columns
# This avoids one-hot categorical features like COUNTRY_NAME_Germany
# ============================================================

valid_rows = []

for _, row in relevant_features_by_segment.iterrows():
    segment = row["country_segment"]
    feature = row["clean_feature"]
    
    if feature in segment_user_model_dfs[segment].columns:
        valid_rows.append(row)

relevant_features_by_segment = pd.DataFrame(valid_rows)

# ============================================================
# 4. Build descriptive table
# ============================================================

feature_descriptions = []

for _, row in relevant_features_by_segment.iterrows():
    segment = row["country_segment"]
    feature = row["clean_feature"]
    importance = row["importance"]
    importance_pct = row["importance_pct"]
    
    segment_df = segment_user_model_dfs[segment]
    
    desc = (
        segment_df
        .groupby("IS_FRAUD_USER")[feature]
        .describe()
        .reset_index()
    )
    
    desc.insert(0, "country_segment", segment)
    desc.insert(1, "feature", feature)
    desc.insert(2, "importance", importance)
    desc.insert(3, "importance_pct", importance_pct)
    
    feature_descriptions.append(desc)

feature_description_table = pd.concat(
    feature_descriptions,
    ignore_index=True
)

feature_description_table

   country_segment                        feature  importance  importance_pct  IS_FRAUD_USER    count          mean              std    min      25%       50%       75%               max
0               UK                 avg_amount_gbp        0.46           45.74          False 3,207.00 19,092,185.44   633,827,737.97   0.00 2,416.05  4,888.03  9,472.44 32,305,515,716.97
1               UK                 avg_amount_gbp        0.46           45.74           True   231.00    211,068.16     2,626,445.23 100.00 6,674.17 21,299.52 50,370.04     39,950,113.96
2               UK             share_currency_GBP        0.28           27.68          False 3,207.00          0.79             0.27   0.00     0.60      0.95      1.00              1.00
3               UK             share_currency_GBP        0.28           27.68           True   231.00          0.98             0.08   0.20     1.00      1.00      1.00              1.00
4               UK       share_type_BANK_TRANSFER        0.10            9.81          False 3,207.00          0.05             0.12   0.00     0.00      0.00      0.05              1.00
5               UK       share_type_BANK_TRANSFER        0.10            9.81           True   231.00          0.13             0.14   0.00     0.00      0.09      0.22              0.57
6               UK                  outlier_share        0.05            4.87          False 3,207.00          0.13             0.17   0.00     0.01      0.08      0.18              1.00
7               UK                  outlier_share        0.05            4.87           True   231.00          0.35             0.25   0.00     0.14      0.33      0.51              1.00
8               UK        share_type_CARD_PAYMENT        0.04            3.64          False 3,207.00          0.46             0.29   0.00     0.22      0.53      0.70              1.00
9               UK        share_type_CARD_PAYMENT        0.04            3.64           True   231.00          0.27             0.25   0.00     0.05      0.21      0.44              0.88
10              UK             cross_border_share        0.03            3.09          False 3,207.00          0.83             0.23   0.00     0.73      0.95      1.00              1.00
11              UK             cross_border_share        0.03            3.09           True   231.00          0.62             0.28   0.08     0.37      0.64      0.85              1.00
12              UK      unique_merchant_countries        0.03            2.64          False 3,207.00          5.16             4.45   1.00     2.00      4.00      7.00             47.00
13              UK      unique_merchant_countries        0.03            2.64           True   231.00          2.48             1.63   1.00     2.00      2.00      3.00             19.00
14              UK                            AGE        0.02            1.71          False 3,207.00         43.09            11.86  26.00    34.00     40.00     49.00             96.00
15              UK                            AGE        0.02            1.71           True   231.00         38.69             9.71  26.00    32.00     36.00     42.50             81.00
16              UK             share_currency_CHF        0.01            0.82          False 3,207.00          0.00             0.03   0.00     0.00      0.00      0.00              0.62
17              UK             share_currency_CHF        0.01            0.82           True   231.00          0.00             0.01   0.00     0.00      0.00      0.00              0.11
18          NON_UK             share_currency_GBP        0.73           72.77          False 3,522.00          0.05             0.17   0.00     0.00      0.00      0.00              1.00
19          NON_UK             share_currency_GBP        0.73           72.77           True    29.00          0.67             0.35   0.00     0.40      0.75      1.00              1.00
20          NON_UK                 avg_amount_gbp        0.14           13.98          False 3,522.00 30,002,218.26 1,069,263,693.97   0.00 1,055.01  2,944.08  6,589.68 60,268,649,369.79
21          NON_UK                 avg_amount_gbp        0.14           13.98           True    29.00     25,800.77        48,878.66 311.33 5,541.19  7,130.81 19,629.37        246,603.24
22          NON_UK  max_same_amount_count_by_user        0.10           10.01          False 3,522.00          7.32            12.73   1.00     2.00      4.00      7.00            298.00
23          NON_UK  max_same_amount_count_by_user        0.10           10.01           True    29.00          4.00             5.22   1.00     1.00      2.00      4.00             26.00
24          NON_UK                            AGE        0.03            3.23          False 3,522.00         42.75            10.83  26.00    35.00     40.00     48.00             98.00
25          NON_UK                            AGE        0.03            3.23           True    29.00         36.21             6.77  26.00    31.00     36.00     38.00             50.00

In [381]:
uk_country_name = "United Kingdom of Great Britain and Northern Ireland (the)"

df["COUNTRY_SEGMENT"] = np.where(
    df["COUNTRY_NAME"] == uk_country_name,
    "UK",
    "NON_UK"
)

country_currency_concentration = (
    df.groupby("COUNTRY_SEGMENT")
    .agg(
        transactions=("USER_ID", "count"),
        unique_users=("USER_ID", "nunique"),

        gbp_transactions=("CURRENCY", lambda x: (x == "GBP").sum()),

        total_amount_gbp=("AMOUNT_GBP", "sum"),
        fraud_amount_gbp=("AMOUNT_GBP", lambda x: x[df.loc[x.index, "IS_FRAUD"]].sum()),

        fraud_transactions=("IS_FRAUD", "sum"),
        fraud_unique_users=("USER_ID", lambda x: df.loc[x.index][df.loc[x.index, "IS_FRAUD"]]["USER_ID"].nunique())
    )
    .reset_index()
)

# Share of total dataset
country_currency_concentration["transaction_share_pct"] = (
    country_currency_concentration["transactions"] / len(df) * 100
).round(2)

country_currency_concentration["user_share_pct"] = (
    country_currency_concentration["unique_users"] / df["USER_ID"].nunique() * 100
).round(2)

country_currency_concentration["amount_gbp_share_pct"] = (
    country_currency_concentration["total_amount_gbp"] / df["AMOUNT_GBP"].sum() * 100
).round(2)

country_currency_concentration["fraud_amount_gbp_share_pct"] = (
    country_currency_concentration["fraud_amount_gbp"] /
    df.loc[df["IS_FRAUD"], "AMOUNT_GBP"].sum() * 100
).round(2)

country_currency_concentration["fraud_transaction_share_pct"] = (
    country_currency_concentration["fraud_transactions"] /
    df["IS_FRAUD"].sum() * 100
).round(2)

country_currency_concentration["fraud_unique_user_share_pct"] = (
    country_currency_concentration["fraud_unique_users"] /
    df.loc[df["IS_FRAUD"], "USER_ID"].nunique() * 100
).round(2)

# GBP concentration within segment
country_currency_concentration["gbp_transaction_share_within_segment_pct"] = (
    country_currency_concentration["gbp_transactions"] /
    country_currency_concentration["transactions"] * 100
).round(2)

# Fraud rates within segment
country_currency_concentration["transaction_fraud_rate_pct"] = (
    country_currency_concentration["fraud_transactions"] /
    country_currency_concentration["transactions"] * 100
).round(2)

country_currency_concentration["user_fraud_rate_pct"] = (
    country_currency_concentration["fraud_unique_users"] /
    country_currency_concentration["unique_users"] * 100
).round(2)

country_currency_concentration["amount_fraud_rate_pct"] = (
    country_currency_concentration["fraud_amount_gbp"] /
    country_currency_concentration["total_amount_gbp"] * 100
).round(2)

country_currency_concentration

  COUNTRY_SEGMENT  transactions  unique_users  gbp_transactions      total_amount_gbp  fraud_amount_gbp  fraud_transactions  fraud_unique_users  transaction_share_pct  user_share_pct  amount_gbp_share_pct  fraud_amount_gbp_share_pct  fraud_transaction_share_pct  fraud_unique_user_share_pct  gbp_transaction_share_within_segment_pct  transaction_fraud_rate_pct  user_fraud_rate_pct  amount_fraud_rate_pct
0          NON_UK        303308          4123             27908 18,621,379,869,937.62     28,327,363.53                1455                  30                  44.04           51.40                 69.65                        1.07                        10.00                        10.03                                      9.20                        0.48                 0.73                   0.00
1              UK        385343          3898            311183  8,116,060,034,849.60  2,621,539,437.58               13088                 269                  55.96           48.60                 30.35                       98.93                        90.00                        89.97                                     80.75                        3.40                 6.90                   0.03

In [382]:
user_model_df.head()

                                USER_ID  IS_FRAUD_USER  AGE COUNTRY_NAME  total_transactions  avg_amount_gbp  unique_types  unique_currencies  unique_merchant_countries  cross_border_transactions  different_currency_transactions  outlier_transactions  max_same_amount_count_by_user  max_same_amount_count_by_user_type  cross_border_share  different_currency_share  outlier_share  share_type_ATM  share_type_BANK_TRANSFER  share_type_CARD_PAYMENT  share_type_P2P  share_type_TOPUP  share_currency_AED  share_currency_AUD  share_currency_BTC  share_currency_CAD  share_currency_CHF  share_currency_CZK  share_currency_DKK  share_currency_ETH  share_currency_EUR  share_currency_GBP  share_currency_HKD  share_currency_HUF  share_currency_ILS  share_currency_INR  share_currency_JPY  share_currency_LTC  share_currency_MAD  share_currency_NOK  share_currency_NZD  share_currency_PLN  share_currency_QAR  share_currency_RON  share_currency_SEK  share_currency_SGD  share_currency_THB  share_currency_TRY  share_currency_USD  share_currency_XRP  share_currency_ZAR  share_currency_type_CRYPTO  share_currency_type_FIAT COUNTRY_SEGMENT
0  000e88bb-d302-4fdc-b757-2b1a2c33e7d6          False   37      Denmark                  16        1,876.31             4                  2                          2                         16                                3                     0                              2                                   2                1.00                      0.19           0.00            0.00                      0.06                     0.50            0.12              0.31                0.00                0.00                0.00                0.00                0.00                0.00                0.81                0.00                0.19                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                        0.00                      1.00          NON_UK
1  001032e0-8071-4baf-95b9-e50214665c2e          False   49        Spain                  36        4,788.37             3                  2                          4                         27                               36                     7                              6                                   6                0.75                      1.00           0.19            0.06                      0.00                     0.64            0.00              0.31                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.69                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.31                0.00                0.00                        0.00                      1.00          NON_UK
2  00131af8-66f0-4526-8b5f-dc2fdb26c7d7          False   40     Portugal                   7        1,618.15             2                  1                          2                          4                                7                     0                              2                                   2                0.57                      1.00           0.00            0.00                      0.00                     0.43            0.00              0.57                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                1.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                        0.00                      1.00          NON_UK
3  001926be-3245-43fa-86dd-b40ee160b6f9          False   50    Gibraltar                 254        5,681.80             4                  2                          4                        249                              254                    33                             18                                  12                0.98                      1.00           0.13            0.08                      0.00                     0.63            0.06              0.23                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.29                0.71                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                        0.00                      1.00          NON_UK
4  001cc034-5730-47c6-a70c-25f42249c9ee          False   40      Romania                   4        1,571.02             2                  2                          1                          4                                2                     0                              2                                   2                1.00                      0.50           0.00            0.00                      0.50                     0.00            0.00              0.50                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.50                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.00                0.50                0.00                0.00                0.00                0.00                0.00                0.00                0.00                        0.00                      1.00          NON_UK

#### Bonus Challange

In [383]:
df.head()

                                USER_ID          TYPE CURRENCY     KYC  IS_FRAUD                                                COUNTRY_NAME MERCHANT_COUNTRY_NAME                                       CURRENCY_COUNTRY_NAME  CROSS_BORDER_TRANSACTION  DIFFERENT_CURRENCY_TRANSACTION  AMOUNT_GBP CURRENCY_TYPE  FLAG_OUTLIER  SAME_AMOUNT_GBP_TX_COUNT_BY_USER  SAME_AMOUNT_GBP_TX_COUNT_BY_USER_TYPE  AGE COUNTRY_SEGMENT
0  7285c1ec-31d0-4022-b311-0ad9227ef7f4  CARD_PAYMENT      GBP  PASSED     False  United Kingdom of Great Britain and Northern Ireland (the)             Australia  United Kingdom of Great Britain and Northern Ireland (the)                      True                           False    3,738.00          FIAT         False                                 1                                      1   63              UK
1  20100a1d-12bc-41ed-a5e1-bc46216e9696  CARD_PAYMENT      GBP  PASSED     False  United Kingdom of Great Britain and Northern Ireland (the)                Canada  United Kingdom of Great Britain and Northern Ireland (the)                      True                           False      588.00          FIAT         False                                 1                                      1   38              UK
2  0fe472c9-cf3e-4e43-90f3-a0cfb6a4f1f0  CARD_PAYMENT      GBP  PASSED     False  United Kingdom of Great Britain and Northern Ireland (the)               Ukraine  United Kingdom of Great Britain and Northern Ireland (the)                      True                           False    1,264.00          FIAT         False                                 1                                      1   49              UK
3  20100a1d-12bc-41ed-a5e1-bc46216e9696  CARD_PAYMENT      GBP  PASSED     False  United Kingdom of Great Britain and Northern Ireland (the)                Canada  United Kingdom of Great Britain and Northern Ireland (the)                      True                           False       66.00          FIAT         False                                 1                                      1   38              UK
4  821014c5-af06-40ff-91f4-77fe7667809f  CARD_PAYMENT      GBP  FAILED     False  United Kingdom of Great Britain and Northern Ireland (the)           New Zealand  United Kingdom of Great Britain and Northern Ireland (the)                      True                           False      968.00          FIAT         False                                 1                                      1   34              UK

In [396]:
# ============================================================
# User-level fraudster table with prioritisation score
# Bonus challenge: Top 5 Fraudsters for Head of Risk
# ============================================================

import numpy as np
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 2000)
pd.set_option("display.max_colwidth", None)
pd.set_option("display.float_format", "{:,.2f}".format)

# ------------------------------------------------------------
# 1. Copy dataset and create helper columns
# ------------------------------------------------------------

df_fraudster = df[df["KYC"] == "PASSED"].copy()

df_fraudster["FRAUD_AMOUNT"] = np.where(
    df_fraudster["IS_FRAUD"] == True,
    df_fraudster["AMOUNT_GBP"],
    0
)

df_fraudster["ATM_TRANSACTION"] = np.where(
    df_fraudster["TYPE"] == "ATM",
    1,
    0
)

df_fraudster["BANK_TRANSFER_TRANSACTION"] = np.where(
    df_fraudster["TYPE"] == "BANK_TRANSFER",
    1,
    0
)

df_fraudster["ATM_AMOUNT"] = np.where(
    df_fraudster["TYPE"] == "ATM",
    df_fraudster["AMOUNT_GBP"],
    0
)

df_fraudster["BANK_TRANSFER_AMOUNT"] = np.where(
    df_fraudster["TYPE"] == "BANK_TRANSFER",
    df_fraudster["AMOUNT_GBP"],
    0
)

# ------------------------------------------------------------
# 2. Country-level totals to use as country denominators
# ------------------------------------------------------------

country_totals = df_fraudster.groupby("COUNTRY_NAME", dropna=False).agg(
    country_transactions=("USER_ID", "count"),
    country_fraud_transactions=("IS_FRAUD", "sum"),
    country_amount=("AMOUNT_GBP", "sum"),
    country_fraud_amount=("FRAUD_AMOUNT", "sum"),
    country_unique_users=("USER_ID", "nunique"),
    country_fraudster_users=(
        "USER_ID",
        lambda x: df_fraudster.loc[x.index][
            df_fraudster.loc[x.index, "IS_FRAUD"]
        ]["USER_ID"].nunique()
    )
).reset_index()

# ------------------------------------------------------------
# 3. Total dataset denominators
# ------------------------------------------------------------

total_transactions = len(df_fraudster)
total_fraud_transactions = df_fraudster["IS_FRAUD"].sum()
total_amount = df_fraudster["AMOUNT_GBP"].sum()
total_fraud_amount = df_fraudster["FRAUD_AMOUNT"].sum()
total_unique_users = df_fraudster["USER_ID"].nunique()
total_fraudster_users = df_fraudster.loc[
    df_fraudster["IS_FRAUD"], "USER_ID"
].nunique()

# ------------------------------------------------------------
# 4. User-level fraudster table
# ------------------------------------------------------------

fraudster_table = df_fraudster.groupby("USER_ID").agg(
    country_name=("COUNTRY_NAME", "first"),
    kyc_status=("KYC", "first"),

    total_transactions=("USER_ID", "count"),
    fraud_transactions=("IS_FRAUD", "sum"),

    atm_transactions=("ATM_TRANSACTION", "sum"),
    bank_transfer_transactions=("BANK_TRANSFER_TRANSACTION", "sum"),
    atm_amount=("ATM_AMOUNT", "sum"),
    bank_transfer_amount=("BANK_TRANSFER_AMOUNT", "sum"),

    total_amount=("AMOUNT_GBP", "sum"),
    fraud_amount=("FRAUD_AMOUNT", "sum"),

    avg_amount=("AMOUNT_GBP", "mean"),
    median_amount=("AMOUNT_GBP", "median"),
    max_amount=("AMOUNT_GBP", "max"),

    unique_types=("TYPE", "nunique"),
    unique_currencies=("CURRENCY", "nunique"),
    unique_merchant_countries=("MERCHANT_COUNTRY_NAME", "nunique")
).reset_index()

# Keep only users with at least one fraud transaction
fraudster_table = fraudster_table[
    fraudster_table["fraud_transactions"] > 0
].copy()

# Since this is user-level, each row represents one fraudster user
fraudster_table["unique_users"] = 1
fraudster_table["fraudster_users"] = 1

# ------------------------------------------------------------
# 5. Merge country denominators into user-level table
# ------------------------------------------------------------

fraudster_table = fraudster_table.merge(
    country_totals,
    left_on="country_name",
    right_on="COUNTRY_NAME",
    how="left"
)

fraudster_table = fraudster_table.drop(columns=["COUNTRY_NAME"])

# ------------------------------------------------------------
# 6. User-level internal rates
# ------------------------------------------------------------

fraudster_table["fraud_rate_pct"] = (
    fraudster_table["fraud_transactions"] /
    fraudster_table["total_transactions"] * 100
).replace([np.inf, -np.inf], 0).fillna(0).round(2)

fraudster_table["atm_transaction_share_pct"] = (
    fraudster_table["atm_transactions"] /
    fraudster_table["total_transactions"] * 100
).replace([np.inf, -np.inf], 0).fillna(0).round(2)

fraudster_table["bank_transfer_transaction_share_pct"] = (
    fraudster_table["bank_transfer_transactions"] /
    fraudster_table["total_transactions"] * 100
).replace([np.inf, -np.inf], 0).fillna(0).round(2)

fraudster_table["atm_amount_share_pct"] = (
    fraudster_table["atm_amount"] /
    fraudster_table["total_amount"] * 100
).replace([np.inf, -np.inf], 0).fillna(0).round(2)

fraudster_table["bank_transfer_amount_share_pct"] = (
    fraudster_table["bank_transfer_amount"] /
    fraudster_table["total_amount"] * 100
).replace([np.inf, -np.inf], 0).fillna(0).round(2)

# Cash-out = ATM + BANK_TRANSFER
fraudster_table["cashout_amount"] = (
    fraudster_table["atm_amount"] +
    fraudster_table["bank_transfer_amount"]
)

fraudster_table["cashout_amount_share_pct"] = (
    fraudster_table["cashout_amount"] /
    fraudster_table["total_amount"] * 100
).replace([np.inf, -np.inf], 0).fillna(0).round(2)

# ------------------------------------------------------------
# 7. Share vs total dataset
# ------------------------------------------------------------

fraudster_table["share_total_transactions_pct"] = (
    fraudster_table["total_transactions"] /
    total_transactions * 100
).round(2)

fraudster_table["share_total_fraud_transactions_pct"] = (
    fraudster_table["fraud_transactions"] /
    total_fraud_transactions * 100
).replace([np.inf, -np.inf], 0).fillna(0).round(2)

fraudster_table["share_total_amount_pct"] = (
    fraudster_table["total_amount"] /
    total_amount * 100
).round(2)

fraudster_table["share_total_fraud_amount_pct"] = (
    fraudster_table["fraud_amount"] /
    total_fraud_amount * 100
).replace([np.inf, -np.inf], 0).fillna(0).round(2)

# ------------------------------------------------------------
# 8. Share vs user's country
# ------------------------------------------------------------

fraudster_table["share_country_transactions_pct"] = (
    fraudster_table["total_transactions"] /
    fraudster_table["country_transactions"] * 100
).replace([np.inf, -np.inf], 0).fillna(0).round(2)

fraudster_table["share_country_fraud_transactions_pct"] = (
    fraudster_table["fraud_transactions"] /
    fraudster_table["country_fraud_transactions"] * 100
).replace([np.inf, -np.inf], 0).fillna(0).round(2)

fraudster_table["share_country_amount_pct"] = (
    fraudster_table["total_amount"] /
    fraudster_table["country_amount"] * 100
).replace([np.inf, -np.inf], 0).fillna(0).round(2)

fraudster_table["share_country_fraud_amount_pct"] = (
    fraudster_table["fraud_amount"] /
    fraudster_table["country_fraud_amount"] * 100
).replace([np.inf, -np.inf], 0).fillna(0).round(2)

# ------------------------------------------------------------
# 9. Global ranks
# ------------------------------------------------------------

fraudster_table["rank_global_fraud_amount"] = fraudster_table["fraud_amount"].rank(
    ascending=False,
    method="dense"
).astype(int)

fraudster_table["rank_global_avg_amount"] = fraudster_table["avg_amount"].rank(
    ascending=False,
    method="dense"
).astype(int)

fraudster_table["rank_global_country_fraud_amount_share"] = fraudster_table[
    "share_country_fraud_amount_pct"
].rank(
    ascending=False,
    method="dense"
).astype(int)

fraudster_table["rank_global_cashout_amount_share"] = fraudster_table[
    "cashout_amount_share_pct"
].rank(
    ascending=False,
    method="dense"
).astype(int)

# ------------------------------------------------------------
# 10. Country rank by fraud amount
# ------------------------------------------------------------

fraudster_table["rank_country_fraud_amount"] = (
    fraudster_table
    .groupby("country_name")["fraud_amount"]
    .rank(ascending=False, method="dense")
    .astype(int)
)

fraudster_table["max_country_fraud_amount_rank"] = (
    fraudster_table
    .groupby("country_name")["rank_country_fraud_amount"]
    .transform("max")
    .astype(int)
)

fraudster_table["country_fraud_amount_rank_position"] = (
    fraudster_table["rank_country_fraud_amount"].astype(str) +
    " / " +
    fraudster_table["max_country_fraud_amount_rank"].astype(str)
)

# ------------------------------------------------------------
# 11. Priority score
# No fraud purity logic, because fraud is tagged at user level.
# Higher score = higher priority.
# ------------------------------------------------------------

fraudster_table["score_fraud_amount"] = fraudster_table["fraud_amount"].rank(
    ascending=True,
    pct=True
)

fraudster_table["score_avg_amount"] = fraudster_table["avg_amount"].rank(
    ascending=True,
    pct=True
)

fraudster_table["score_country_fraud_amount_share"] = fraudster_table[
    "share_country_fraud_amount_pct"
].rank(
    ascending=True,
    pct=True
)

fraudster_table["score_cashout_amount"] = fraudster_table[
    "cashout_amount"
].rank(
    ascending=True,
    pct=True
)

fraudster_table["score_cashout_amount_share"] = fraudster_table[
    "cashout_amount_share_pct"
].rank(
    ascending=True,
    pct=True
)

fraudster_table["priority_score"] = (
    fraudster_table["score_fraud_amount"] * 0.20 +
    fraudster_table["score_avg_amount"] * 0.25 +
    fraudster_table["score_country_fraud_amount_share"] * 0.05 +
    fraudster_table["score_cashout_amount"] * 0.35 +
    fraudster_table["score_cashout_amount_share"] * 0.10
).round(4)

fraudster_table["rank_priority"] = fraudster_table["priority_score"].rank(
    ascending=False,
    method="dense"
).astype(int)

# ------------------------------------------------------------
# 12. Final analytical view
# ------------------------------------------------------------

fraudster_table_view = fraudster_table.sort_values(
    [
        "priority_score",
        "fraud_amount",
        "avg_amount",
        "share_country_fraud_amount_pct",
        "cashout_amount_share_pct"
    ],
    ascending=[False, False, False, False, False]
).reset_index(drop=True)

fraudster_table_view = fraudster_table_view[
    [
        "USER_ID",
        "country_name",
        "kyc_status",

        "priority_score",
        "rank_priority",
        "score_fraud_amount",
        "score_avg_amount",
        "score_country_fraud_amount_share",
        "score_cashout_amount",
        "score_cashout_amount_share",

        #"total_transactions",
        "fraud_transactions",
        "fraud_rate_pct",

        #"total_amount",
        "fraud_amount",
        "avg_amount",
        "median_amount",
        "max_amount",

        "share_total_fraud_amount_pct",
        "share_country_fraud_amount_pct",

        "cashout_amount",
        "cashout_amount_share_pct",
        "atm_amount_share_pct",
        "bank_transfer_amount_share_pct",

        "rank_global_fraud_amount",
        "rank_global_avg_amount",
        "rank_global_country_fraud_amount_share",
        "rank_global_cashout_amount_share",
        "country_fraud_amount_rank_position",

        "unique_types",
        "unique_currencies",
        "unique_merchant_countries"
    ]
]

fraudster_table_view.head()

                                USER_ID                                                country_name kyc_status  priority_score  rank_priority  score_fraud_amount  score_avg_amount  score_country_fraud_amount_share  score_cashout_amount  score_cashout_amount_share  fraud_transactions  fraud_rate_pct  fraud_amount  avg_amount  median_amount   max_amount  share_total_fraud_amount_pct  share_country_fraud_amount_pct  cashout_amount  cashout_amount_share_pct  atm_amount_share_pct  bank_transfer_amount_share_pct  rank_global_fraud_amount  rank_global_avg_amount  rank_global_country_fraud_amount_share  rank_global_cashout_amount_share country_fraud_amount_rank_position  unique_types  unique_currencies  unique_merchant_countries
0  310667d1-92c6-4fc7-83f1-55b61773ace5  United Kingdom of Great Britain and Northern Ireland (the)     PASSED            0.91              1                1.00              0.98                              0.89                  1.00                        0.69                  60          100.00 11,826,891.96  197,114.87       1,995.00 2,072,685.14                          0.88                            0.89    5,863,069.96                     49.57                  0.00                           49.57                         2                       6                                      25                                71                            2 / 230             4                  3                          3
1  88c417b7-c081-4b37-a88a-c5b368ba0a08  United Kingdom of Great Britain and Northern Ireland (the)     PASSED            0.89              2                0.96              0.95                              0.85                  0.97                        0.82                  37          100.00  4,627,781.00  125,075.16      80,000.00 2,238,241.00                          0.34                            0.35    2,334,200.00                     50.44                 42.79                            7.65                        11                      15                                      32                                47                           11 / 230             4                  1                          2
2  40a70d7d-447d-426c-872e-012658b2b98c  United Kingdom of Great Britain and Northern Ireland (the)     PASSED            0.89              3                0.97              0.89                              0.86                  0.98                        0.88                  53          100.00  4,801,988.00   90,603.55      70,000.00   850,000.00                          0.36                            0.36    2,479,000.00                     51.62                 51.62                            0.00                        10                      29                                      31                                31                           10 / 230             3                  1                          2
3  4f41a015-5205-467d-98d6-a90d343e8afb  United Kingdom of Great Britain and Northern Ireland (the)     PASSED            0.89              4                0.96              0.89                              0.85                  0.98                        0.92                  51          100.00  4,598,174.00   90,160.27      50,000.00 2,000,000.00                          0.34                            0.35    2,437,000.00                     53.00                 53.00                            0.00                        12                      30                                      32                                23                           12 / 230             3                  1                          2
4  c1192087-81c9-4328-89a0-398f33cb91de  United Kingdom of Great Britain and Northern Ireland (the)     PASSED            0.88              5                0.93              1.00                              0.83                  0.94                        0.72                  12          100.00  4,002,126.00  333,510.50      26,000.00 2,000,000.00                          0.30                            0.30    1,991,500.00                     49.76                  1.10                           48.66                        18                       2                                      36                                63                           17 / 230             4                  1                          2